import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {fixture,admin,anonymous} from './local-fixtures.mjs';
const ok=async p=>{const r=await p;assert.equal(r.error,null,JSON.stringify(r.error));return r.data;};
test('place report assignment, customer revision and closure persist without changing facts or private trip notes',async()=>{
 const f=await fixture();let place;
 try{const owner=await f.actor(),outsider=await f.actor(),ops=await f.actor();await ok(admin.from('kinnso_ops_members').insert({user_id:ops.id,display_name:'Synthetic report operator',role:'moderator'}));
 place=randomUUID();await ok(admin.from('places').insert({id:place,name:'Synthetic report place',timezone:'UTC'}));await ok(admin.from('kinnso_place_facts').insert({place_id:place,timezone:'UTC',published:false,source_url:'https://example.test/private-review'}));
 let trip=await ok(owner.client.rpc('create_trip_v2',{p_request_id:randomUUID(),p_payload:{title:'Report private trip',timezone:'UTC'}}));const day=randomUUID();trip=await ok(owner.client.rpc('apply_trip_command',{p_trip_id:trip.id,p_expected_revision:trip.revision,p_request_id:randomUUID(),p_command:{type:'addDay',id:day,offset:0,title:'Private day'}}));trip=await ok(owner.client.rpc('apply_trip_command',{p_trip_id:trip.id,p_expected_revision:trip.revision,p_request_id:randomUUID(),p_command:{type:'addStop',id:randomUUID(),dayId:day,position:0,input:{title:'Private title',placeId:place,travellerNote:'Must remain private and unchanged',startMinuteOfDay:null,durationMinutes:null}}}));
 const report=await ok(owner.client.rpc('report_kinnso_place',{p_place_id:place,p_reason:'Opening hours need author verification'}));assert.equal((await ok(outsider.client.rpc('get_kinnso_place_report_queue'))).items.length,0);
 const command=(actor,revision,type,reason,extra={})=>({actor,args:{p_report_id:report.id,p_expected_revision:revision,p_request_id:randomUUID(),p_command:{type,reason,...extra}}});
 let action=command(ops,1,'assign','Assigned local operator for review',{ownerId:ops.id});const assigned=await ok(ops.client.rpc('apply_kinnso_place_report_command',action.args));assert.equal(assigned.assignedTo,ops.id);assert.equal(assigned.revision,2);assert.deepEqual(await ok(ops.client.rpc('apply_kinnso_place_report_command',action.args)),assigned);
 action=command(ops,2,'requestRevision','Please provide the source and observed date');await ok(ops.client.rpc('apply_kinnso_place_report_command',action.args));assert.equal((await ok(owner.client.rpc('get_kinnso_inbox'))).items.filter(x=>x.type==='place.report_revision').length,1);
 assert.equal((await outsider.client.rpc('apply_kinnso_place_report_command',command(outsider,3,'revise','Foreign actor must never rewrite report').args)).error?.message,'report_not_found');
 await ok(owner.client.rpc('apply_kinnso_place_report_command',command(owner,3,'revise','Source and observed date added by original reporter').args));assert.equal((await ops.client.rpc('apply_kinnso_place_report_command',command(ops,3,'resolve','Stale revision must not close report').args)).error?.message,'revision_conflict');
 action=command(ops,4,'resolve','Reviewed source and closed without editing facts');const closed=await ok(ops.client.rpc('apply_kinnso_place_report_command',action.args));assert.equal(closed.status,'resolved');assert.equal(closed.revision,5);assert.deepEqual(await ok(ops.client.rpc('apply_kinnso_place_report_command',action.args)),closed);
 assert.equal((await ok(ops.client.rpc('get_kinnso_place_report_queue',{p_ops:true}))).items.some(r=>r.id===report.id),false);const inbox=await ok(owner.client.rpc('get_kinnso_inbox'));assert.equal(inbox.items.filter(x=>x.type==='place.report_resolved').length,1);assert.equal((await ok(owner.client.rpc('get_kinnso_place_report_queue'))).items[0].status,'resolved');assert.deepEqual(await ok(owner.client.rpc('get_trip_snapshot',{p_trip_id:trip.id})),trip);assert.equal((await anonymous.from('kinnso_place_facts').select('*').eq('place_id',place)).data.length,0);
 await ok(admin.from('kinnso_ops_members').update({status:'paused'}).eq('user_id',ops.id));assert.equal((await ops.client.rpc('apply_kinnso_place_report_command',action.args)).error?.message,'forbidden');assert.equal((await ops.client.rpc('get_kinnso_place_report_queue',{p_ops:true})).error?.message,'forbidden');
 }finally{if(place)await ok(admin.from('places').delete().eq('id',place));await f.cleanup();}
});
test('agent quota is fixed to the fresh actor and atomically enforces 20 calls without caller-selected identity',async()=>{
 const f=await fixture();try{const actor=await f.actor(),other=await f.actor();assert.ok((await anonymous.rpc('take_kinnso_agent_quota')).error);const results=await Promise.all(Array.from({length:25},()=>actor.client.rpc('take_kinnso_agent_quota')));assert.ok(results.every(r=>!r.error));assert.equal(results.filter(r=>r.data===true).length,20);assert.equal(await ok(other.client.rpc('take_kinnso_agent_quota')),true);assert.ok((await actor.client.schema('kinnso_internal').from('agent_quota').select('*')).error);assert.ok((await actor.client.rpc('take_kinnso_agent_quota',{actor_id:other.id})).error);await actor.client.auth.signOut();assert.ok((await actor.client.rpc('take_kinnso_agent_quota')).error);}finally{await f.cleanup();}
});
