'use client';
import {useRef,useState} from 'react';import Link from 'next/link';
import * as demo from './model';import {useApp} from './ui';
import {previewLocalImport,type ImportPreview as Preview} from '../../lib/trips/import';
import {request} from '../../lib/trips/repository';import type {TripSnapshot} from '../../lib/contracts/trips';
import {readGuestTrips,type GuestTrip} from '../../lib/trips/guest-drafts';
export function ImportPreview({actorId}:{actorId:string|null}) {
 const {t,href}=useApp(),[guests,setGuests]=useState<GuestTrip[]>([]),[candidates,setCandidates]=useState<demo.Trip[]>([]),[owner,setOwner]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const intent=useRef<{key:string;requestId:string}|null>(null);
 function load(){try{const store=demo.read();if(!store.session){setMessage(t('Open and export your own demo account first.','請先開啟及匯出你的示範帳戶。'));return}setOwner(store.session.id);setCandidates(demo.tripsFor(store).filter(trip=>trip.purpose==='personal'));setMessage('')}catch{setMessage(t('Local data needs recovery; it has not been replaced.','本機資料需要復原，原資料並未取代。'))}}
 return <section className="os-guide os-stop"><h2>{t('Preview and import local trips','預覽及匯入本機行程')}</h2><p>{t('Your original data stays on this device. Creator credit and business records are excluded.','原資料會保留於此裝置。創作者授權標識及商業紀錄不會匯入。')}</p><p>{t('Device drafts can be read by anyone using this browser. Only preview your own copies on a shared device.','此瀏覽器的使用者均可讀取裝置草稿。共用裝置上請只預覽自己的副本。')}</p><button className="k-btn" onClick={load}>{t('Preview this device’s current demo account','預覽此裝置目前的示範帳戶')}</button>
 <button className="k-btn" onClick={async()=>{try{const rows=await readGuestTrips(),valid=rows.filter(trip=>trip&&typeof trip.id==='string'&&/^[\w-]{1,100}$/.test(trip.id)&&typeof trip.ownerId==='string'&&/^guest-[\w-]{1,94}$/.test(trip.ownerId)&&trip.purpose==='personal'&&previewLocalImport(trip,trip.ownerId).ok);setGuests(valid);setMessage(rows.length===valid.length?'':t('Some device copies could not be previewed. Original data is kept.','部分裝置副本未能預覽，原資料已保留。'))}catch{setMessage(t('Device draft storage is unavailable.','裝置草稿無法讀取。'))}}}>{t('Preview device-only drafts','預覽裝置草稿')}</button><ul>{guests.map(trip=><li key={trip.id}><button className="k-btn" onClick={()=>setPreview(previewLocalImport(trip,trip.ownerId))}>{trip.title}</button></li>)}</ul><ul>{candidates.map(trip=><li key={trip.id}><button className="k-btn" onClick={()=>setPreview(previewLocalImport(trip,owner))}>{trip.title}</button></li>)}</ul>
 {preview?.ok&&<div><p>{t('Local identity','本機身份')}: {preview.localOwnerId} · {preview.payload.title}</p><p>{preview.payload.days.length} {t('days','日')} · {preview.payload.pendingPhotos.length} {t('photos pending separate upload','張照片待另行上載')}</p><p>{t('Source credits will be unverified. The signed-in server account becomes the owner.','來源標識將視為未驗證。擁有人由已登入 server 帳戶決定。')}</p>
 {actorId?<button className="k-btn primary" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);const key=JSON.stringify(preview.payload);if(intent.current?.key!==key)intent.current={key,requestId:crypto.randomUUID()};const result=await request<TripSnapshot&{pendingPhotos:unknown[]}>('/api/trips/import','POST',{requestId:intent.current.requestId,sourceId:preview.sourceId,payload:preview.payload});if(result.ok){setMessage(result.data.pendingPhotos.length?t('Trip imported; photos are still pending. Original files are kept.','行程已匯入；照片仍待處理，原檔保留。'):t('Trip imported to your account.','行程已匯入你的帳戶。'));intent.current=null}else setMessage(result.code==='CONFLICT'?t('This source changed. Keep the original and review before retrying.','來源內容已有變更，請保留原資料並核對後重試。'):t('Import was not confirmed. Original data is kept.','未確認匯入完成，原資料保留。'));setBusy(false)}}>{t('Confirm import to this account','確認匯入此帳戶')}</button>:<Link className="k-btn primary" href={href('sign-in')+'?next='+encodeURIComponent(href('trips'))}>{t('Sign in and return to preview','登入後返回預覽')}</Link>}</div>}
 {preview&&!preview.ok&&<p role="alert">{t('This local trip cannot be imported safely. Export the original for recovery.','此本機行程未能安全匯入，請匯出原資料以便復原。')}</p>}<p role="status">{message}</p></section>
}
