'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useApp} from './ui';
import {subscribeAccountInvalidation} from '../../lib/trips/local-drafts';
import {inbox,support,deliveryFailures,entityLink,type InboxPage,type InboxCursor,type SupportCase,type DeliveryFailure} from '../../lib/notifications/repository';
export function InboxWorkspace({actorId,enabled}:{actorId:string|null;enabled:boolean}){
 const{t,locale}=useApp();const[data,setData]=useState<InboxPage|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[valid,setValid]=useState(true),[unknown,setUnknown]=useState(false);
 const generation=useRef(0),pending=useRef<{command:Record<string,unknown>;id:string}|null>(null);
 function clear(){setData(null);pending.current=null;setUnknown(false);}
 async function load(cursor?:InboxCursor){const own=++generation.current;setBusy(true);const r=await inbox.get(cursor);if(own!==generation.current)return;setBusy(false);if(!r.ok){clear();setError(r.code);return;}setData(r.data);setError('');}
 useEffect(()=>{setValid(true);clear();setError('');const unsub=subscribeAccountInvalidation(next=>{if(next!==actorId){++generation.current;setValid(false);clear();}});if(actorId&&enabled)void load();return()=>{++generation.current;unsub();};},[actorId,enabled]);
 async function send(command?:Record<string,unknown>){if(!pending.current&&command)pending.current={command,id:crypto.randomUUID()};const p=pending.current;if(!p)return;const own=++generation.current;setBusy(true);const r=await inbox.command(p.command,p.id);if(own!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clear();setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;return;}pending.current=null;setUnknown(false);await load();}
 return <section className="k-page"><h1>{t('Your inbox','你的收件匣')}</h1>{!actorId||!valid?<Link href={`/${locale}/sign-in?next=/${locale}/inbox`}>{t('Sign in','登入')}</Link>:!enabled?<p>{t('Inbox service is not connected yet.','收件匣服務尚未接通。')}</p>:<>
 {error&&<p role="alert">{t('Inbox request was not completed. Refresh or retry.','收件匣請求未完成，請重新載入或重試。')}</p>}<button className="k-btn" disabled={busy||unknown} onClick={()=>void load()}>{t('Refresh inbox','重新載入收件匣')}</button>{unknown&&<button className="k-btn" disabled={busy} onClick={()=>void send()}>{t('Retry the same request','重試相同請求')}</button>}
 {data&&<><p>{data.unreadCount} {t('unread notifications','項未讀通知')}</p><p>{t('Email delivery is not configured. These are in-app notifications.','電郵外送尚未設定；這些是站內通知。')}</p><button className="k-btn" disabled={busy||unknown} onClick={()=>void send({type:'setPreference',channel:'email',enabled:false})}>{t('Opt out of future email delivery','取消未來電郵外送')}</button>{data.items.length===0&&<p>{t('No notifications yet.','暫未有通知。')}</p>}
 {data.items.map(item=><article className="k-card" key={item.id}><h2>{item.type}</h2><p>{item.payload.missionTitle}</p><time dateTime={item.createdAt}>{item.createdAt}</time><p>{item.readAt?t('Read','已讀'):t('Unread','未讀')}</p>{entityLink(item,locale)&&<Link href={entityLink(item,locale)!}>{t('Open related activity','開啟相關活動')}</Link>}<button className="k-btn" disabled={busy||unknown||!!item.readAt} onClick={()=>void send({type:'markRead',id:item.id})}>{t('Mark as read','標示已讀')}</button><Link href={`/${locale}/support?event=${item.id}`}>{t('Ask support about this event','向客服查詢此事件')}</Link></article>)}{data.nextCursor&&<button className="k-btn" disabled={busy||unknown} onClick={()=>void load(data.nextCursor!)}>{t('Older notifications','較早通知')}</button>}</>}
 <Link className="k-btn" href={`/${locale}/support`}>{t('Support cases','客服案件')}</Link></>}</section>;
}
export function SupportWorkspace({actorId,enabled,opsMode=false}:{actorId:string|null;enabled:boolean;opsMode?:boolean}){
 const{t,locale}=useApp();const[items,setItems]=useState<SupportCase[]|null>(null),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[valid,setValid]=useState(true),[unknown,setUnknown]=useState(false),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[status,setStatus]=useState('in_progress');
 const generation=useRef(0),pending=useRef<{command:Record<string,unknown>;id:string}|null>(null);
 function clear(){setItems(null);setCursor(null);pending.current=null;setUnknown(false);setSubject('');setMessage('');setReason('');}
 async function load(after?:string){const own=++generation.current;setBusy(true);const r=await support.list(opsMode,after);if(own!==generation.current)return;setBusy(false);if(!r.ok){clear();setError(r.code);return;}setItems(r.data.items);setCursor(r.data.nextCursor);setError('');}
 async function older(c:SupportCase){if(!c.messagesNextCursor)return;const own=++generation.current;setBusy(true);const r=await support.messages(c.id,c.messagesNextCursor,opsMode);if(own!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clear();setError(r.code);return;}setItems(rows=>rows?.map(row=>row.id===c.id?{...row,messages:[...r.data.items,...row.messages],messagesNextCursor:r.data.nextCursor}:row)??null);setError('');}
 useEffect(()=>{setValid(true);clear();setError('');const unsub=subscribeAccountInvalidation(next=>{if(next!==actorId){++generation.current;setValid(false);clear();}});if(actorId&&enabled)void load();return()=>{++generation.current;unsub();};},[actorId,enabled,opsMode]);
 async function send(command?:Record<string,unknown>){if(!pending.current&&command)pending.current={command,id:crypto.randomUUID()};const p=pending.current;if(!p)return;const own=++generation.current;setBusy(true);const r=await support.command(p.command,p.id);if(own!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clear();setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;return;}pending.current=null;setUnknown(false);setMessage('');await load();}
 const locked=busy||unknown;
 return <section className="k-page"><h1>{opsMode?t('Support queue','客服待辦'):t('Your support cases','你的客服案件')}</h1>{!actorId||!valid?<Link href={`/${locale}/sign-in?next=/${locale}/support`}>{t('Sign in','登入')}</Link>:!enabled?<p>{t('Support service is not connected yet.','客服服務尚未接通。')}</p>:<>
 {error&&<p role="alert">{error==='CONFLICT'?t('This case changed. Refresh before submitting again.','案件已有變動，請重新載入後提交。'):t('Support request was not completed. Refresh or retry.','客服請求未完成，請重新載入或重試。')}</p>}<button className="k-btn" disabled={locked} onClick={()=>void load()}>{t('Refresh cases','重新載入案件')}</button>{unknown&&<button className="k-btn" disabled={busy} onClick={()=>void send()}>{t('Retry the same request','重試相同請求')}</button>}
 {!opsMode&&<form className="k-card" onSubmit={e=>{e.preventDefault();const event=new URLSearchParams(window.location.search).get('event');void send({type:'create',id:crypto.randomUUID(),subject,message,...event?{linkedEventId:event}:{}});}}><label>{t('Case subject','案件主題')}<input aria-label={t('Case subject','案件主題')} required maxLength={200} disabled={locked} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>{t('Message to support','給客服的訊息')}<textarea aria-label={t('Message to support','給客服的訊息')} required maxLength={4000} disabled={locked} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="k-btn primary" disabled={locked}>{t('Create support case','建立客服案件')}</button></form>}
 {opsMode&&<div className="k-card"><label>{t('Case decision','案件決定')}<select aria-label={t('Case decision','案件決定')} disabled={locked} value={status} onChange={e=>setStatus(e.target.value)}>{['in_progress','waiting_customer','resolved'].map(x=><option key={x}>{x}</option>)}</select></label><label>{t('Internal decision reason','內部決定原因')}<textarea aria-label={t('Internal decision reason','內部決定原因')} disabled={locked} minLength={10} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>{t('Response visible to the customer','客戶可見的回覆')}<textarea aria-label={t('Response visible to the customer','客戶可見的回覆')} disabled={locked} maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label><p>{t('A response is required when asking for details or resolving a case.','要求補充資料或結案時必須填寫回覆。')}</p></div>}
 {items?.length===0&&<p>{t('No support cases.','沒有客服案件。')}</p>}{items?.map(c=><article className="k-card" key={c.id}><h2>{c.subject}</h2><p>{c.status} · {t('Assigned owner','指派負責人')}: {c.ownerId??t('Unassigned','未指派')}</p><time dateTime={c.updatedAt}>{t('Last updated','最後更新')} {c.updatedAt}</time>{c.messagesNextCursor&&<button className="k-btn" disabled={locked} onClick={()=>void older(c)}>{t('Load older messages','載入較早訊息')}</button>}{c.messages.map(m=><p key={m.id}>{m.message}</p>)}{opsMode?<button className="k-btn" disabled={locked||reason.trim().length<10||(['waiting_customer','resolved'].includes(status)&&!message.trim())} onClick={()=>void send({type:'review',id:c.id,expectedRevision:c.revision,ownerId:actorId,status,reason,...message.trim()?{message}:{}})}>{t('Assign to me and apply decision','指派予我並套用決定')}</button>:c.status!=='resolved'&&<form onSubmit={e=>{e.preventDefault();void send({type:'reply',id:c.id,expectedRevision:c.revision,message});}}><label>{t('Reply to this case','回覆此案件')}<textarea aria-label={t('Reply to this case','回覆此案件')} required maxLength={4000} disabled={locked} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="k-btn" disabled={locked}>{t('Send case reply','提交案件回覆')}</button></form>}</article>)}{cursor&&<button className="k-btn" disabled={locked} onClick={()=>void load(cursor!)}>{t('Next cases','下一頁案件')}</button>}
 {opsMode&&<DeliveryFailures actorId={actorId} enabled={enabled}/>}
 </>}</section>;
}
function DeliveryFailures({actorId,enabled}:{actorId:string|null;enabled:boolean}){
 const{t}=useApp();const[items,setItems]=useState<DeliveryFailure[]|null>(null),[cursor,setCursor]=useState<string|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[valid,setValid]=useState(true);
 const generation=useRef(0),pending=useRef<{command:{id:string;expectedRevision:number;reason:string};requestId:string}|null>(null);
 function clear(){setItems(null);setCursor(null);setReason('');setUnknown(false);pending.current=null;}
 async function load(after?:string){const own=++generation.current;setBusy(true);const r=await deliveryFailures.list(after);if(own!==generation.current)return;setBusy(false);if(!r.ok){clear();setError(r.code);return;}setItems(r.data.items);setCursor(r.data.nextCursor);setError('');}
 useEffect(()=>{setValid(true);clear();const unsubscribe=subscribeAccountInvalidation(next=>{if(next!==actorId){++generation.current;setValid(false);clear();}});if(actorId&&enabled)void load();return()=>{++generation.current;unsubscribe();};},[actorId,enabled]);
 async function retry(item?:DeliveryFailure){if(item&&!pending.current)pending.current={command:{id:item.id,expectedRevision:item.revision,reason},requestId:crypto.randomUUID()};const p=pending.current;if(!p)return;const own=++generation.current;setBusy(true);const r=await deliveryFailures.retry(p.command,p.requestId);if(own!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clear();setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;setError(r.code);return;}pending.current=null;setUnknown(false);setReason('');await load();}
 if(!valid||!actorId||!enabled)return null;
 return <section className="k-card"><h2>{t('Failed email deliveries','外送失敗的電郵')}</h2><p>{t('An approved retry starts at most five more attempts for the same event. It does not repeat the business action.','核准重試會為相同事件啟動最多五次外送嘗試，不會重複業務操作。')}</p>{error&&<p role="alert">{error==='CONFLICT'?t('Delivery changed. Refresh before retrying.','外送狀態已變更，請重新載入。'):t('Delivery queue request was not completed.','外送佇列請求未完成。')}</p>}<button className="k-btn" disabled={busy||unknown} onClick={()=>void load()}>{t('Refresh failed deliveries','重新載入外送失敗項目')}</button>{unknown&&<button className="k-btn" disabled={busy} onClick={()=>void retry()}>{t('Retry the same request','重試相同請求')}</button>}<label>{t('Internal reason for retry','重試的內部原因')}<textarea disabled={busy||unknown} value={reason} minLength={10} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label>{items?.length===0&&<p>{t('No failed deliveries.','沒有外送失敗項目。')}</p>}{items?.map(item=><article key={item.id}><p>{item.channel} · {item.eventId} · {item.attempts} {t('attempts','次嘗試')}</p><button className="k-btn" disabled={busy||unknown||reason.trim().length<10} onClick={()=>void retry(item)}>{t('Authorize bounded retry','核准有限次重試')}</button></article>)}{cursor&&<button className="k-btn" disabled={busy||unknown} onClick={()=>void load(cursor!)}>{t('Next failed deliveries','下一頁外送失敗項目')}</button>}</section>;
}
