'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useApp} from './ui';
import {subscribeAccountInvalidation} from '../../lib/trips/local-drafts';
import {merchants,type Membership,type MerchantWorkspaceDTO,type Redemption} from '../../lib/merchants/repository';
import {MerchantTeamAccess} from './MerchantTeamAccess';
import {parseCommissionPercent} from '../../lib/merchants/access';
export function MerchantWorkspace({actorId,enabled}:{actorId:string|null;enabled:boolean}){
 const{t,locale}=useApp();const[valid,setValid]=useState(true),[memberships,setMemberships]=useState<Membership[]|null>(null),[merchantId,setMerchantId]=useState(''),[data,setData]=useState<MerchantWorkspaceDTO|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[message,setMessage]=useState(''),[redemption,setRedemption]=useState<Redemption|null>(null);
 const[branchName,setBranchName]=useState(''),[branchId,setBranchId]=useState(''),[teamRefreshKey,setTeamRefreshKey]=useState(0),[code,setCode]=useState(''),[amount,setAmount]=useState('');
 const[title,setTitle]=useState(''),[summary,setSummary]=useState(''),[couponCode,setCouponCode]=useState(''),[couponUrl,setCouponUrl]=useState(''),[rates,setRates]=useState(['','','']);
 const epoch=useRef(0),workspaceEpoch=useRef(0),pending=useRef<{kind:'command'|'redeem';merchantId:string;command?:Record<string,unknown>;code?:string;branchId?:string;amount?:number|null;requestId:string}|null>(null);
 const locked=busy||unknown;
 function clearDrafts(){setBranchName('');setBranchId('');setCode('');setAmount('');setTitle('');setSummary('');setCouponCode('');setCouponUrl('');setRates(['','','']);pending.current=null;setUnknown(false);setBusy(false);}
 useEffect(()=>{const own=++epoch.current;setValid(true);setMemberships(null);setMerchantId('');setData(null);setError('');pending.current=null;setUnknown(false);setMessage('');setRedemption(null);setCode('');setAmount('');
  clearDrafts();const unsubscribe=subscribeAccountInvalidation(next=>{if(next!==actorId){epoch.current++;workspaceEpoch.current++;setValid(false);setData(null);setMemberships(null);clearDrafts();}});
  if(actorId&&enabled)void merchants.memberships().then(r=>{if(own!==epoch.current)return;if(!r.ok){setError(r.code);return;}setMemberships(r.data);setMerchantId(r.data[0]?.merchantId??'');});
  return()=>{epoch.current++;unsubscribe();};},[actorId,enabled]);
 useEffect(()=>{const own=++workspaceEpoch.current,account=epoch.current;setData(null);setBranchId('');setMessage('');setRedemption(null);pending.current=null;setUnknown(false);
  clearDrafts();
  if(merchantId)void merchants.workspace(merchantId).then(r=>{if(own!==workspaceEpoch.current||account!==epoch.current)return;if(!r.ok){setError(r.code);return;}setData(r.data);setBranchId(r.data.branches[0]?.id??'');setError('');});return()=>{workspaceEpoch.current++;};},[merchantId]);
 async function refresh(cursors:{after?:string;applicationsAfter?:string;outcomesAfter?:string}={}){const own=epoch.current,scope=workspaceEpoch.current;const r=await merchants.workspace(merchantId,cursors);if(own!==epoch.current||scope!==workspaceEpoch.current)return;if(!r.ok){setData(null);setCode('');setRedemption(null);setMessage('');pending.current=null;setUnknown(false);setError(r.code);return;}setData(r.data);setBranchId(current=>r.data.branches.some(x=>x.id===current)?current:r.data.branches[0]?.id??'');setError('');}
 async function send(command?:Record<string,unknown>){const own=epoch.current,scope=workspaceEpoch.current;
  pending.current??=command?{kind:'command',merchantId,command,requestId:crypto.randomUUID()}:{kind:'redeem',merchantId,code,branchId,amount:amount===''?null:Number(amount),requestId:crypto.randomUUID()};
  const p=pending.current;setBusy(true);const r=p.kind==='command'?await merchants.command(p.merchantId,p.command!,p.requestId):await merchants.redeem(p.code!,p.branchId!,p.requestId,p.amount!);if(own!==epoch.current||scope!==workspaceEpoch.current)return;setBusy(false);
  if(!r.ok){setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED'){setData(null);clearDrafts();setRedemption(null);}return;}
  pending.current=null;setUnknown(false);setError('');if(p.kind==='redeem'){setRedemption(r.data as Redemption);setCode('');setAmount('');}else{setMessage(t('Saved on the server.','已儲存至伺服器。'));setBranchName('');setTeamRefreshKey(value=>value+1);}await refresh();
 }
 if(!actorId||!valid)return <section className="k-page"><h1>{t('Merchant workspace','商戶工作區')}</h1><Link href={`/${locale}/sign-in?next=/${locale}/merchant`}>{t('Sign in to continue','登入後繼續')}</Link></section>;
 if(!enabled)return <section className="k-page"><h1>{t('Merchant workspace','商戶工作區')}</h1><p>{t('Merchant services are not connected yet.','商戶服務尚未接通。')}</p></section>;
 return <section className="k-page"><h1>{t('Merchant workspace','商戶工作區')}</h1>{error&&<p role="alert">{error==='FORBIDDEN'?t('Your current company or branch access does not allow this action.','目前公司或分店權限不允許此操作。'):error==='INVALID'?t('Check the entered details or offer availability.','請核對資料或優惠有效狀態。'):t('Could not complete this request. Retry or refresh.','未能完成請求，請重試或重新整理。')}</p>}{message&&<p role="status">{message}</p>}
 {!memberships&&!error&&<p role="status">{t('Loading company access…','正在載入公司權限…')}</p>}{memberships?.length===0&&<p>{t('No active company access is assigned to this account.','此帳戶未獲分配有效公司權限。')}</p>}
 {!!memberships?.length&&<label>{t('Company','公司')}<select aria-label={t('Company','公司')} value={merchantId} disabled={locked} onChange={e=>setMerchantId(e.target.value)}>{memberships.map(m=><option key={m.merchantId} value={m.merchantId}>{m.name}</option>)}</select></label>}
 <button className="k-btn" disabled={!merchantId||locked} onClick={()=>void refresh()}>{t('Refresh workspace','重新載入工作區')}</button>
 {unknown&&<button className="k-btn" disabled={busy} onClick={()=>void send()}>{t('Retry the same request','重試相同請求')}</button>}
 {data&&<><p>{t('Current organization role','目前組織角色')} · {data.role==='owner'?t('Owner','擁有人'):data.role==='marketing'?t('Marketing','推廣'):data.role==='clerk'?t('Branch clerk','分店店員'):t('Finance','財務')}</p><p>{t('Funding and payment are unavailable here. Outcome amounts show recorded settlement obligations, not available budget.','此處尚未開通資金及付款；結果金額顯示已記錄的結算責任，不代表可用預算。')}</p>
 {data.role==='owner'&&<div className="k-card"><h2>{t('Branches and access','分店及權限')}</h2><form onSubmit={e=>{e.preventDefault();void send({type:'createBranch',id:crypto.randomUUID(),name:branchName,reason:'Owner created branch'});}}><label>{t('Branch name','分店名稱')}<input required maxLength={120} value={branchName} disabled={locked} onChange={e=>setBranchName(e.target.value)}/></label><button className="k-btn" disabled={locked||!branchName.trim()}>{t('Create branch','建立分店')}</button></form>
 <MerchantTeamAccess actorId={actorId} merchantId={merchantId} branches={data.branches} refreshKey={teamRefreshKey} locked={locked} onSave={send} onDenied={code=>{workspaceEpoch.current++;setData(null);clearDrafts();setRedemption(null);setMessage('');setError(code);}}/></div>}
 {['owner','marketing'].includes(data.role)&&<div className="k-card"><h2>{t('Create coupon promotion brief','建立優惠推廣簡報')}</h2><form onSubmit={e=>{e.preventDefault();const percentages=rates.map(parseCommissionPercent);if(percentages.some(value=>value===null)){setError('INVALID');return;}void send({type:'createBrief',id:crypto.randomUUID(),title,summary,couponCode,couponUrl,affiliateRate:percentages[0],kinnsoRate:percentages[1],creatorRate:percentages[2],publish:true,requirements:[],deliverables:[],reason:'Merchant confirmed published coupon brief'});}}>
 <label>{t('Brief title','簡報標題')}<input required maxLength={120} value={title} disabled={locked} onChange={e=>setTitle(e.target.value)}/></label><label>{t('Brief description','簡報內容')}<textarea aria-label={t('Brief description','簡報內容')} required maxLength={5000} value={summary} disabled={locked} onChange={e=>setSummary(e.target.value)}/></label><label>{t('Coupon code','優惠碼')}<input required value={couponCode} disabled={locked} onChange={e=>setCouponCode(e.target.value)}/></label><label>{t('Coupon URL','優惠網址')}<input required type="url" value={couponUrl} disabled={locked} onChange={e=>setCouponUrl(e.target.value)}/></label>{[['Affiliate commission rate (%)','聯盟佣金比例（%）'],['Platform commission rate (%)','平台佣金比例（%）'],['Creator commission rate (%)','創作者佣金比例（%）']].map(([en,zh],i)=><label key={en}>{t(en,zh)}<input required type="number" min="0" step="0.01" value={rates[i]} disabled={locked} onChange={e=>setRates(rates.map((x,n)=>n===i?e.target.value:x))}/></label>)}<p>{t('Enter percentage values: 70 means70%;0.70 means0.70%. Confirm the commercial split separately.','請輸入百分比數值：70代表70%；0.70代表0.70%。商業分配須另行確認。')}</p><p>{t('Confirm the promotion details before publishing. Paid campaigns need separate commercial approval.','發布前請確認推廣資料；付費活動須另有商業批准。')}</p><button className="k-btn primary" disabled={locked}>{t('Publish promotion brief','發布推廣簡報')}</button></form>
 <h2>{t('Promotion progress','推廣進度')}</h2>{data.missions.map(m=><article className="k-card" key={m.id}><h3>{m.title}</h3><p>{m.summary}</p><p>{m.status} · {m.missionType}</p></article>)}{data.nextCursor&&<button className="k-btn" disabled={locked} onClick={()=>void refresh({after:data.nextCursor!})}>{t('Next promotions','下一頁推廣')}</button>}
 <h2>{t('Applications awaiting review','待審申請')}</h2>{data.applications.map(a=><article className="k-card" key={a.id}><h3>{a.missionTitle}</h3><p>{a.creatorId} · {a.note}</p>{['approve','reject'].map(action=><button className="k-btn" key={action} disabled={locked} onClick={()=>void send({type:'reviewApplication',id:a.id,expectedStatus:a.status,action,note:'Merchant reviewed application',reason:'Merchant confirmed application '+action})}>{action==='approve'?t('Approve application','批准申請'):t('Reject application','拒絕申請')}</button>)}</article>)}{data.applicationsNextCursor&&<button className="k-btn" disabled={locked} onClick={()=>void refresh({applicationsAfter:data.applicationsNextCursor!})}>{t('Next applications','下一頁申請')}</button>}</div>}
 {['owner','clerk'].includes(data.role)&&<div className="k-card"><h2>{t('Redeem at this branch','此分店核銷')}</h2><form onSubmit={e=>{e.preventDefault();setRedemption(null);void send();}}><label>{t('Redemption branch','核銷分店')}<select aria-label={t('Redemption branch','核銷分店')} required value={branchId} disabled={locked} onChange={e=>setBranchId(e.target.value)}><option value="">{t('Select branch','選擇分店')}</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>{t('Visitor redemption code','旅客核銷碼')}<input required autoComplete="off" maxLength={2048} value={code} disabled={locked} onChange={e=>setCode(e.target.value)}/></label><label>{t('Amount spent, required for percentage offers','消費金額，百分比優惠必填')}<input type="number" min="0" step="0.01" value={amount} disabled={locked} onChange={e=>setAmount(e.target.value)}/></label><button className="k-btn primary" disabled={locked||!branchId}>{t('Confirm redemption','確認核銷')}</button></form>{redemption&&<p role="status">{redemption.expired?t('This claim has expired; no redemption was created.','此領取已過期，未建立核銷。'):redemption.already_redeemed?t('This visitor code was already redeemed.','此旅客碼已核銷。'):t('Redemption recorded.','核銷已記錄。')}</p>}</div>}
 <div className="k-card"><h2>{t('Recorded outcomes in your branch scope','分店權限範圍內的已記錄結果')}</h2>{data.outcomes.length===0?<p>{t('No recorded redemptions in your scope.','你的權限範圍未有核銷紀錄。')}</p>:data.outcomes.map(o=><article key={o.id}><p>{o.redeemedAt} · {t('Recorded outcome state','已記錄結果狀態')}: {o.state}</p><p>{t('Recorded creator commission','已記錄創作者佣金')} · {o.currency??t('Currency not recorded','幣別未記錄')} · {o.creatorAmount??t('No settlement obligation recorded','未記錄結算責任')}</p></article>)}{data.outcomesNextCursor&&<button className="k-btn" disabled={locked} onClick={()=>void refresh({outcomesAfter:data.outcomesNextCursor!})}>{t('Next outcomes','下一頁結果')}</button>}</div>
 </>}</section>;
}
