'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useApp,Modal } from './ui';
import { subscribeAccountInvalidation } from '../../lib/trips/local-drafts';
import { ops, type Routing, type QueueRow, type QueuePreset, type SubmissionDetail,type BulkResult, type CurrencyTotal, type Preview, type QueueCursor, type QueuePage } from '../../lib/ops/repository';
import { deadlineState, queueFilterPath, readQueueFilter, type QueueFilter } from '../../lib/ops/queue-filters';
export function OpsWorkspace({actorId,enabled}:{actorId:string|null;enabled:boolean}){
 const {t,locale}=useApp();const [valid,setValid]=useState(true),[page,setPage]=useState<QueuePage|null>(null),[totals,setTotals]=useState<CurrencyTotal[]|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Preview|null>(null),[result,setResult]=useState<BulkResult|null>(null),[reason,setReason]=useState(''),[action,setAction]=useState('request_revision'),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false);
 const pending=useRef<{jobId:string;action:string;reason:string;requestId:string}|null>(null);
 const generation=useRef(0),evidenceOpener=useRef<HTMLElement|null>(null);
 const [detail,setDetail]=useState<SubmissionDetail|null>(null);
 const [filter,setFilter]=useState<QueueFilter>({});
 const [routing,setRouting]=useState<Routing|null>(null),[presetName,setPresetName]=useState('');
 const [assignment,setAssignment]=useState<{row:QueueRow;memberId:string}|null>(null),[assignmentReason,setAssignmentReason]=useState('');
 const routingPending=useRef<{type:'assignment';args:Parameters<typeof ops.assign>}|{type:'preset';args:Parameters<typeof ops.preset>}|null>(null);
 const assignmentOpener=useRef<HTMLElement|null>(null);
 function clearPreview(){setPreview(null);setResult(null);pending.current=null;setUnknown(false);}
 function clearPrivate(){clearPreview();setDetail(null);setPage(null);setTotals(null);setSelected([]);setReason('');setAction('request_revision');setRouting(null);setAssignment(null);setAssignmentReason('');setPresetName('');routingPending.current=null;}
 async function inspect(id:string,opener:HTMLElement){evidenceOpener.current=opener;const current=++generation.current;setBusy(true);const r=await ops.detail(id);if(current!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clearPrivate();setError(r.code);return;}setDetail(r.data);}
 async function load(nextFilter:QueueFilter=filter,cursor?:QueueCursor){const current=++generation.current;clearPrivate();setBusy(true);setError('');const [q,s,r]=await Promise.all([ops.queue(nextFilter,cursor),ops.summary(nextFilter.missionId),ops.routing()]);if(current!==generation.current)return;setBusy(false);if(!q.ok||!s.ok||(!r.ok&&(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED'))){clearPrivate();setError(!q.ok?q.code:!s.ok?s.code:!r.ok?r.code:'UNAVAILABLE');return;}setPage(q.data);setTotals(s.data);if(r.ok)setRouting(r.data);setSelected([]);setError('');}
 async function changeFilter(next:QueueFilter){setFilter(next);window.history.replaceState(null,'',queueFilterPath(locale,next));await load(next);}
 useEffect(()=>{setValid(true);clearPrivate();setError('');setBusy(false);
  const unsubscribe=subscribeAccountInvalidation(next=>{if(next!==actorId){++generation.current;setValid(false);clearPrivate();setBusy(false);}});
  const initial=readQueueFilter(new URLSearchParams(window.location.search));
  if(!initial)setError('INVALID_FILTER');else{setFilter(initial);if(actorId&&enabled)void load(initial);}
  return()=>{++generation.current;unsubscribe();};},[actorId,enabled,locale]);
 async function prepare(ids=selected){const current=++generation.current;clearPreview();setBusy(true);const r=await ops.preview(ids);if(current!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clearPrivate();setError(r.code);return;}setPreview(r.data);setError('');}
 async function run(){if(!preview)return;const current=++generation.current;pending.current??={jobId:preview.jobId,action,reason,requestId:crypto.randomUUID()};const p=pending.current;setBusy(true);const r=await ops.run(p.jobId,p.action,'other',p.reason,p.requestId);if(current!==generation.current)return;setBusy(false);
  if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clearPrivate();setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;return;}setUnknown(false);pending.current=null;setResult(r.data);setError('');}
 async function runRouting(){const p=routingPending.current;if(!p)return;const current=++generation.current;setBusy(true);setError('');
  const r=p.type==='assignment'?await ops.assign(...p.args):await ops.preset(...p.args);if(current!==generation.current)return;setBusy(false);
  if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED'){clearPrivate();setError(r.code);return;}setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')routingPending.current=null;return;}
  routingPending.current=null;setUnknown(false);setAssignment(null);await load();
 }
 async function confirmAssignment(){if(!assignment||!assignmentReason.trim()||routingPending.current)return;
  routingPending.current={type:'assignment',args:[assignment.row.submissionId,assignment.memberId||null,assignment.row.assignmentRevision??0,assignmentReason,crypto.randomUUID()]};await runRouting();
 }
 async function savePreset(preset?:QueuePreset,remove=false){if(routingPending.current)return;
  routingPending.current={type:'preset',args:[preset?.id??crypto.randomUUID(),preset?.revision??0,crypto.randomUUID(),remove?{type:'delete'}:{type:'save',name:preset?.name??presetName,filter:{...filter}}]};await runRouting();
 }
 if(!actorId||!valid)return <section className="k-page"><h1>{t('Operations queue','營運待辦')}</h1><Link href={`/${locale}/sign-in?next=${encodeURIComponent(queueFilterPath(locale,filter))}`}>{t('Sign in to continue','登入後繼續')}</Link></section>;
 if(!enabled)return <section className="k-page"><h1>{t('Operations queue','營運待辦')}</h1><p>{t('Operations access is not connected yet.','營運服務尚未接通。')}</p></section>;
 const missions=new Map((page?.items??[]).map(row=>[row.missionId,row.missionTitle]));if(filter.missionId&&!missions.has(filter.missionId))missions.set(filter.missionId,t('Mission from filter link','篩選連結中的活動'));
 return <section className="k-page"><h1>{t('Operations queue','營運待辦')}</h1>{error&&<p role="alert">{error==='FORBIDDEN'?t('Active operations access is required.','需要有效營運權限。'):error==='INVALID_FILTER'?t('This filter link is invalid. Reset filters to continue.','此篩選連結無效，請重設篩選。'):t('The request could not be completed. Refresh or retry.','請求未能完成，請重新整理或重試。')}</p>}
 <div className="k-card"><h2>{t('Queue filters','待辦篩選')}</h2><label>{t('Mission','活動')}<select aria-label={t('Mission','活動')} value={filter.missionId??''} disabled={busy||unknown} onChange={e=>void changeFilter({...filter,missionId:e.target.value||undefined})}><option value="">{t('All missions','全部活動')}</option>{[...missions].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><p>{t('Mission options come from the displayed page or the current filter link.','活動選項來自本頁或目前的篩選連結。')}</p>
 <label>{t('Review status','審核狀態')}<select aria-label={t('Review status','審核狀態')} value={filter.status??''} disabled={busy||unknown} onChange={e=>void changeFilter({...filter,status:e.target.value as QueueFilter['status']||undefined})}><option value="">{t('All reviewable statuses','全部可審狀態')}</option><option value="submitted">{t('Submitted','已提交')}</option><option value="revision_requested">{t('Revision requested','已要求修訂')}</option></select></label>
 <button className="k-btn" disabled={busy||unknown} onClick={()=>void changeFilter({})}>{t('Reset filters','重設篩選')}</button><a className="k-btn" href={queueFilterPath(locale,filter)}>{t('Reusable filter link','可重開的篩選連結')}</a><p>{t('Bookmark the link to reopen these criteria. Results and selections are refreshed.','可將連結加入書籤以重開篩選；結果與選取會重新載入。')}</p></div>
 {routing?<div className="k-card"><h2>{t('Assignment and saved filters','指派與已存篩選')}</h2>
 <label>{t('Assignment filter','指派篩選')}<select aria-label={t('Assignment filter','指派篩選')} value={filter.assignment??''} disabled={busy||unknown} onChange={e=>void changeFilter({...filter,assignment:e.target.value as QueueFilter['assignment']||undefined})}><option value="">{t('All assignments','全部指派')}</option><option value="mine">{t('Assigned to me','指派給我')}</option><option value="unassigned">{t('Unassigned','未指派')}</option></select></label>
 <label>{t('Queue order','待辦排序')}<select aria-label={t('Queue order','待辦排序')} value={filter.order??''} disabled={busy||unknown} onChange={e=>void changeFilter({...filter,order:e.target.value==='deadline'?'deadline':undefined})}><option value="">{t('Verification signal, then deadline','核實訊號，再按期限')}</option><option value="deadline">{t('Earliest deadline first','最早期限優先')}</option></select></label>
 <label>{t('Saved filter name','篩選名稱')}<input aria-label={t('Saved filter name','篩選名稱')} value={presetName} maxLength={80} disabled={busy||unknown} onChange={e=>setPresetName(e.target.value)}/></label><button className="k-btn" disabled={busy||unknown||!presetName.trim()||routing.presets.length>=20} onClick={()=>void savePreset()}>{t('Save current filter','儲存目前篩選')}</button><p>{t('Up to 20 private filters. Only criteria are saved; results and selections reload from the server.','最多 20 個私人篩選。只儲存條件；結果與選取會由伺服器重新載入。')}</p>
 {routing.presets.map(preset=><div key={preset.id}><button className="k-btn" disabled={busy||unknown} onClick={()=>void changeFilter(preset.filter)}>{t('Open filter: ','開啟篩選：')+preset.name}</button><button className="k-btn" disabled={busy||unknown} onClick={()=>void savePreset(preset)}>{t('Update with current criteria: ','更新為目前條件：')+preset.name}</button><button className="k-btn" disabled={busy||unknown} onClick={()=>void savePreset(preset,true)}>{t('Delete filter: ','刪除篩選：')+preset.name}</button></div>)}
 {routing.membersTruncated&&<p>{t('The first 200 operations members are listed. Contact an owner for other assignments.','此處列出前 200 位營運成員；其他指派請聯絡 owner。')}</p>}</div>:page&&<p>{t('Assignment and saved filters are not connected yet.','指派與已存篩選尚未接通。')}</p>}
 {unknown&&routingPending.current&&!assignment&&<button className="k-btn" disabled={busy} onClick={()=>void runRouting()}>{t('Retry routing request','重試相同指派／篩選請求')}</button>}
 <button className="k-btn" disabled={busy||unknown} onClick={()=>void load()}>{t('Refresh queue','重新載入待辦')}</button><Link className="k-btn" href={`/${locale}/ops/reports`}>{t('Place report queue','地點回報待辦')}</Link><Link className="k-btn" href={`/${locale}/ops/support`}>{t('Support queue','客服待辦')}</Link>
 {totals&&<div className="k-card"><h2>{t('Server settlement totals','伺服器結算彙總')}</h2><p>{filter.missionId?t('This mission, all settlement statuses. Review-status filtering applies to submissions.','此活動的全部結算狀態；審核狀態篩選適用於提交。'):t('All missions, all settlement statuses. Review-status filtering applies to submissions.','全部活動的全部結算狀態；審核狀態篩選適用於提交。')}</p>{totals.length===0?<p>{t('No settlement records.','沒有結算紀錄。')}</p>:totals.map(x=><p key={x.currency??'unknown'}>{x.currency??t('Currency not recorded','幣別未記錄')} · {x.count} {t('records','項')} · {t('Creator obligation','創作者應付')} {x.creatorAmount} · {t('Paid records','已付項數')} {x.paidCount} · {t('Disputed','爭議')} {x.disputedCount}</p>)}</div>}
 {!page&&!error&&<p role="status">{t('Loading queue…','正在載入待辦…')}</p>}
 {page&&<div className="k-card"><h2>{t('Review submissions','審核提交')}</h2><p>{t('Select this page only. Maximum 100 items per confirmed batch.','僅選取本頁；每次確認批次最多 100 項。')}</p><button className="k-btn" disabled={busy||unknown} onClick={()=>{clearPreview();setSelected(page.items.map(x=>x.submissionId));}}>{t('Select this page','選取本頁')}</button>
 {page.items.length===0&&<p>{t('No submissions awaiting review.','目前沒有待審提交。')}</p>}
 <p>{filter.order==='deadline'?t('Ordered by earliest review deadline across the filtered queue. No deadline is last.','整個篩選待辦按最早審核期限排序，未設定期限的項目排最後。'):t('Ordered by verification signal, then earliest review deadline.','按核實訊號優先，再按最早審核期限排序。')}</p><p>{t('Overdue on this page','本頁逾期項目')}: {page.items.filter(row=>deadlineState(row.reviewDeadline)==='overdue').length}</p>
 {page.items.map(row=><article className="k-card" key={row.submissionId}><label><input type="checkbox" disabled={busy||unknown} checked={selected.includes(row.submissionId)} onChange={e=>{clearPreview();setSelected(e.target.checked?[...selected,row.submissionId]:selected.filter(x=>x!==row.submissionId));}}/>{row.missionTitle}</label><p>{row.status} · {row.confidenceStatus??t('No verification signal','未有核實訊號')} · {deadlineState(row.reviewDeadline)==='overdue'&&<strong>{t('Overdue','已逾期')} · </strong>}{deadlineState(row.reviewDeadline)==='unknown'?t('No deadline recorded','未設定截止時間'):<time dateTime={row.reviewDeadline!}>{new Date(row.reviewDeadline!).toLocaleString(locale)}</time>}</p>
 {routing&&<p>{t('Assigned operator','指派成員')}: {row.assignedMemberId?(routing.members.find(x=>x.id===row.assignedMemberId)?.name??t('Operations member','營運成員')):t('Unassigned','未指派')}{row.assignedMemberId&&!row.assigneeAvailable&&' · '+t('Unavailable; assignment is retained','成員不可用；保留原指派')}</p>}
 {routing?.canAssign&&<button className="k-btn" disabled={busy||unknown} onClick={event=>{clearPreview();assignmentOpener.current=event.currentTarget;setAssignment({row,memberId:row.assignedMemberId??''});setAssignmentReason('');}}>{t('Assign review','指派審核')}</button>}
 <button className="k-btn" disabled={busy||unknown} onClick={event=>void inspect(row.submissionId,event.currentTarget)}>{t('Review evidence','檢視證據')}</button></article>)}
 <button className="k-btn" disabled={!selected.length||busy||unknown} onClick={()=>void prepare()}>{t('Preview selection','預覽選取')}</button>{page.nextCursor&&<button className="k-btn" disabled={busy||unknown} onClick={()=>void load(filter,page.nextCursor!)}>{t('Next page','下一頁')}</button>}</div>}
 {preview&&<div className="k-card"><h2>{t('Confirm this snapshot','確認此選取快照')}</h2><p>{preview.selectionSnapshot.length} {t('explicitly selected items; changes since preview will be rejected.','項明確選取；預覽後變動的項目會被拒絕。')}</p><label>{t('Decision','決定')}<select value={action} disabled={busy||unknown||!!result} onChange={e=>setAction(e.target.value)}><option value="request_revision">{t('Request revision','要求修訂')}</option><option value="reject">{t('Reject','拒絕')}</option><option value="approve">{t('Approve after verification','核實後批准')}</option></select></label><label>{t('Audit reason','審核原因')}<textarea aria-label={t('Audit reason','審核原因')} value={reason} maxLength={2000} disabled={busy||unknown||!!result} onChange={e=>setReason(e.target.value)}/></label>
 {!result&&<button className="k-btn primary" disabled={!reason.trim()||busy} onClick={()=>void run()}>{unknown?t('Retry the same request','重試相同請求'):t('Apply confirmed decision','套用已確認決定')}</button>}
 {result&&<><p role="status">{result.succeeded} {t('succeeded','成功')} · {result.failed} {t('failed','失敗')}</p><p>{t('Batch reference','批次參照')}: {result.jobId}</p>{result.results.filter(x=>!x.ok).map(x=><p key={x.id}>{x.id} · {x.code}</p>)}{result.failed>0&&<button className="k-btn" disabled={busy} onClick={()=>void prepare(result.results.filter(x=>!x.ok).map(x=>x.id))}>{t('Preview only failed items for retry','僅預覽失敗項目以重試')}</button>}</>}
 </div>}{assignment&&routing&&<Modal title={t('Assign review','指派審核')} returnFocus={assignmentOpener.current} onClose={()=>{if(!busy&&!unknown)setAssignment(null);}}><h3>{assignment.row.missionTitle}</h3><p>{t('Assignment routes work; existing review permissions still apply.','指派用於分派工作；原有審核權限仍然適用。')}</p><label>{t('Assigned operator','指派成員')}<select aria-label={t('Assigned operator','指派成員')} value={assignment.memberId} disabled={busy||unknown} onChange={e=>setAssignment({...assignment,memberId:e.target.value})}><option value="">{t('Unassigned','未指派')}</option>{routing.members.map(member=><option key={member.id} value={member.id} disabled={member.status!=='active'||!['owner','admin','moderator'].includes(member.role)}>{member.name??t('Operations member','營運成員')} · {member.role} · {member.status}</option>)}</select></label><label>{t('Assignment reason','指派原因')}<textarea aria-label={t('Assignment reason','指派原因')} value={assignmentReason} maxLength={2000} disabled={busy||unknown} onChange={e=>setAssignmentReason(e.target.value)}/></label>{error&&<p role="alert">{unknown?t('The outcome is unknown. Retry the same request.','結果未明，請重試相同請求。'):t('Assignment could not be completed. Close and refresh the queue.','未能完成指派；請關閉並重新載入待辦。')}</p>}{unknown&&routingPending.current&&<button className="k-btn" disabled={busy} onClick={()=>void runRouting()}>{t('Retry routing request','重試相同指派／篩選請求')}</button>}<button className="k-btn primary" disabled={busy||unknown||!assignmentReason.trim()} onClick={()=>void confirmAssignment()}>{t('Confirm assignment','確認指派')}</button></Modal>}{detail&&<Modal title={t('Submission evidence','提交證據')} returnFocus={evidenceOpener.current} onClose={()=>setDetail(null)}><h3>{detail.missionTitle}</h3><p>{detail.status}</p><p>{detail.notes??t('No notes supplied.','未有提供筆記。')}</p><p>{t('Submitted at','提交時間')}: {detail.submittedAt??t('Unknown','未知')}</p>{detail.proofUrls?.map(url=>{let safe=false;try{const parsed=new URL(url);safe=['http:','https:'].includes(parsed.protocol)&&!parsed.username&&!parsed.password;}catch{}return safe?<a key={url} href={url} target="_blank" rel="noreferrer">{url}</a>:<p key={url}>{t('An invalid proof link was supplied.','提交包含無效證據連結。')}</p>;})}</Modal>}</section>;
}
