'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useApp,Modal } from './ui';
import { subscribeAccountInvalidation } from '../../lib/trips/local-drafts';
import { ops, type SubmissionDetail,type BulkResult, type CurrencyTotal, type Preview, type QueueCursor, type QueuePage } from '../../lib/ops/repository';
export function OpsWorkspace({actorId,enabled}:{actorId:string|null;enabled:boolean}){
 const {t,locale}=useApp();const [valid,setValid]=useState(true),[page,setPage]=useState<QueuePage|null>(null),[totals,setTotals]=useState<CurrencyTotal[]|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Preview|null>(null),[result,setResult]=useState<BulkResult|null>(null),[reason,setReason]=useState(''),[action,setAction]=useState('request_revision'),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false);
 const pending=useRef<{jobId:string;action:string;reason:string;requestId:string}|null>(null);
 const generation=useRef(0),evidenceOpener=useRef<HTMLElement|null>(null);
 const [detail,setDetail]=useState<SubmissionDetail|null>(null);
 function clearPreview(){setPreview(null);setResult(null);pending.current=null;setUnknown(false);}
 function clearPrivate(){clearPreview();setDetail(null);setPage(null);setTotals(null);setSelected([]);setReason('');setAction('request_revision');}
 async function inspect(id:string,opener:HTMLElement){evidenceOpener.current=opener;const current=++generation.current;setBusy(true);const r=await ops.detail(id);if(current!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clearPrivate();setError(r.code);return;}setDetail(r.data);}
 async function load(cursor?:QueueCursor){const current=++generation.current;clearPreview();setBusy(true);const [q,s]=await Promise.all([ops.queue(undefined,cursor),ops.summary()]);if(current!==generation.current)return;setBusy(false);if(!q.ok||!s.ok){clearPrivate();setError(!q.ok?q.code:!s.ok?s.code:'UNAVAILABLE');return;}setPage(q.data);setTotals(s.data);setSelected([]);setError('');}
 useEffect(()=>{setValid(true);clearPrivate();setError('');setBusy(false);
  const unsubscribe=subscribeAccountInvalidation(next=>{if(next!==actorId){++generation.current;setValid(false);clearPrivate();setBusy(false);}});
  if(actorId&&enabled)void load();
  return()=>{++generation.current;unsubscribe();};},[actorId,enabled]);
 async function prepare(ids=selected){const current=++generation.current;clearPreview();setBusy(true);const r=await ops.preview(ids);if(current!==generation.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clearPrivate();setError(r.code);return;}setPreview(r.data);setError('');}
 async function run(){if(!preview)return;const current=++generation.current;pending.current??={jobId:preview.jobId,action,reason,requestId:crypto.randomUUID()};const p=pending.current;setBusy(true);const r=await ops.run(p.jobId,p.action,'other',p.reason,p.requestId);if(current!==generation.current)return;setBusy(false);
  if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clearPrivate();setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;return;}setUnknown(false);pending.current=null;setResult(r.data);setError('');}
 if(!actorId||!valid)return <section className="k-page"><h1>{t('Operations queue','營運待辦')}</h1><Link href={`/${locale}/sign-in?next=/${locale}/ops`}>{t('Sign in to continue','登入後繼續')}</Link></section>;
 if(!enabled)return <section className="k-page"><h1>{t('Operations queue','營運待辦')}</h1><p>{t('Operations access is not connected yet.','營運服務尚未接通。')}</p></section>;
 return <section className="k-page"><h1>{t('Operations queue','營運待辦')}</h1>{error&&<p role="alert">{error==='FORBIDDEN'?t('Active operations access is required.','需要有效營運權限。'):t('The request could not be completed. Refresh or retry.','請求未能完成，請重新整理或重試。')}</p>}
 <button className="k-btn" disabled={busy||unknown} onClick={()=>void load()}>{t('Refresh queue','重新載入待辦')}</button><Link className="k-btn" href={`/${locale}/ops/reports`}>{t('Place report queue','地點回報待辦')}</Link><Link className="k-btn" href={`/${locale}/ops/support`}>{t('Support queue','客服待辦')}</Link>
 {totals&&<div className="k-card"><h2>{t('Server settlement totals','伺服器結算彙總')}</h2>{totals.length===0?<p>{t('No settlement records.','沒有結算紀錄。')}</p>:totals.map(x=><p key={x.currency??'unknown'}>{x.currency??t('Currency not recorded','幣別未記錄')} · {x.count} {t('records','項')} · {t('Creator obligation','創作者應付')} {x.creatorAmount} · {t('Paid records','已付項數')} {x.paidCount} · {t('Disputed','爭議')} {x.disputedCount}</p>)}</div>}
 {!page&&!error&&<p role="status">{t('Loading queue…','正在載入待辦…')}</p>}
 {page&&<div className="k-card"><h2>{t('Review submissions','審核提交')}</h2><p>{t('Select this page only. Maximum 100 items per confirmed batch.','僅選取本頁；每次確認批次最多 100 項。')}</p><button className="k-btn" disabled={busy||unknown} onClick={()=>{clearPreview();setSelected(page.items.map(x=>x.submissionId));}}>{t('Select this page','選取本頁')}</button>
 {page.items.length===0&&<p>{t('No submissions awaiting review.','目前沒有待審提交。')}</p>}
 {page.items.map(row=><article className="k-card" key={row.submissionId}><label><input type="checkbox" disabled={busy||unknown} checked={selected.includes(row.submissionId)} onChange={e=>{clearPreview();setSelected(e.target.checked?[...selected,row.submissionId]:selected.filter(x=>x!==row.submissionId));}}/>{row.missionTitle}</label><p>{row.status} · {row.confidenceStatus??t('No verification signal','未有核實訊號')} · {row.reviewDeadline??t('No deadline recorded','未設定截止時間')}</p><button className="k-btn" disabled={busy||unknown} onClick={event=>void inspect(row.submissionId,event.currentTarget)}>{t('Review evidence','檢視證據')}</button></article>)}
 <button className="k-btn" disabled={!selected.length||busy||unknown} onClick={()=>void prepare()}>{t('Preview selection','預覽選取')}</button>{page.nextCursor&&<button className="k-btn" disabled={busy||unknown} onClick={()=>void load(page.nextCursor!)}>{t('Next page','下一頁')}</button>}</div>}
 {preview&&<div className="k-card"><h2>{t('Confirm this snapshot','確認此選取快照')}</h2><p>{preview.selectionSnapshot.length} {t('explicitly selected items; changes since preview will be rejected.','項明確選取；預覽後變動的項目會被拒絕。')}</p><label>{t('Decision','決定')}<select value={action} disabled={busy||unknown||!!result} onChange={e=>setAction(e.target.value)}><option value="request_revision">{t('Request revision','要求修訂')}</option><option value="reject">{t('Reject','拒絕')}</option><option value="approve">{t('Approve after verification','核實後批准')}</option></select></label><label>{t('Audit reason','審核原因')}<textarea aria-label={t('Audit reason','審核原因')} value={reason} maxLength={2000} disabled={busy||unknown||!!result} onChange={e=>setReason(e.target.value)}/></label>
 {!result&&<button className="k-btn primary" disabled={!reason.trim()||busy} onClick={()=>void run()}>{unknown?t('Retry the same request','重試相同請求'):t('Apply confirmed decision','套用已確認決定')}</button>}
 {result&&<><p role="status">{result.succeeded} {t('succeeded','成功')} · {result.failed} {t('failed','失敗')}</p>{result.results.filter(x=>!x.ok).map(x=><p key={x.id}>{x.id} · {x.code}</p>)}{result.failed>0&&<button className="k-btn" disabled={busy} onClick={()=>void prepare(result.results.filter(x=>!x.ok).map(x=>x.id))}>{t('Preview only failed items for retry','僅預覽失敗項目以重試')}</button>}</>}
 </div>}{detail&&<Modal title={t('Submission evidence','提交證據')} returnFocus={evidenceOpener.current} onClose={()=>setDetail(null)}><h3>{detail.missionTitle}</h3><p>{detail.status}</p><p>{detail.notes??t('No notes supplied.','未有提供筆記。')}</p><p>{t('Submitted at','提交時間')}: {detail.submittedAt??t('Unknown','未知')}</p>{detail.proofUrls?.map(url=>{let safe=false;try{const parsed=new URL(url);safe=['http:','https:'].includes(parsed.protocol)&&!parsed.username&&!parsed.password;}catch{}return safe?<a key={url} href={url} target="_blank" rel="noreferrer">{url}</a>:<p key={url}>{t('An invalid proof link was supplied.','提交包含無效證據連結。')}</p>;})}</Modal>}</section>;
}
