'use client';
import Link from'next/link';import{useEffect,useRef,useState}from'react';import{useApp}from'./ui';import{reports,type PlaceReport}from'../../lib/ops/reports';import{subscribeAccountInvalidation}from'../../lib/trips/local-drafts';
export function ReportWorkspace({actorId,enabled,opsMode=false}:{actorId:string|null;enabled:boolean;opsMode?:boolean}){
 const{t,locale}=useApp();const[rows,setRows]=useState<PlaceReport[]|null>(null),[cursor,setCursor]=useState<string|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[valid,setValid]=useState(true);const epoch=useRef(0),pending=useRef<{row:PlaceReport;command:Record<string,unknown>;id:string}|null>(null);
 function clear(){setRows(null);setCursor(null);setReason('');pending.current=null;setUnknown(false);}
 async function load(after?:string){const own=++epoch.current;setBusy(true);const r=await reports.list(opsMode,after);if(own!==epoch.current)return;setBusy(false);if(!r.ok){clear();setError(r.code);return;}setRows(r.data.items);setCursor(r.data.nextCursor);setError('');}
 useEffect(()=>{setValid(true);clear();setError('');const unsub=subscribeAccountInvalidation(next=>{if(next!==actorId){++epoch.current;setValid(false);clear();setBusy(false);}});if(actorId&&enabled)void load();return()=>{++epoch.current;unsub();};},[actorId,enabled,opsMode]);
 async function send(row?:PlaceReport,type?:string){if(!pending.current&&row&&type)pending.current={row,command:{type,reason,...type==='assign'?{ownerId:actorId}:{}},id:crypto.randomUUID()};const p=pending.current;if(!p)return;const own=++epoch.current;setBusy(true);const r=await reports.command(p.row,p.command,p.id);if(own!==epoch.current)return;setBusy(false);if(!r.ok){if(r.code==='FORBIDDEN'||r.code==='AUTH_REQUIRED')clear();setError(r.code);setUnknown(r.code==='UNAVAILABLE');if(r.code!=='UNAVAILABLE')pending.current=null;return;}pending.current=null;setUnknown(false);setReason('');await load();}
 const locked=busy||unknown;
 return <section className="k-page"><h1>{opsMode?t('Place report queue','地點回報待辦'):t('Your place reports','你的地點回報')}</h1>{!actorId||!valid?<Link href={`/${locale}/sign-in?next=/${locale}/reports`}>{t('Sign in','登入')}</Link>:!enabled?<p>{t('Report workflow is not connected yet.','回報流程尚未接通。')}</p>:<>{error&&<p role="alert">{error==='CONFLICT'?t('This report changed. Refresh before another decision.','回報已有變動，請重新載入後作決定。'):t('Report request could not be completed.','未能完成回報請求。')}</p>}<button className="k-btn" disabled={locked} onClick={()=>void load()}>{t('Refresh reports','重新載入回報')}</button>{unknown&&<button className="k-btn" disabled={busy} onClick={()=>void send()}>{t('Retry the same request','重試相同請求')}</button>}<label>{opsMode?t('Review reason','審核原因'):t('Revised report details','修訂回報內容')}<textarea aria-label={opsMode?t('Review reason','審核原因'):t('Revised report details','修訂回報內容')} minLength={10} maxLength={2000} disabled={locked} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {rows?.length===0&&<p>{t('No reports in this queue.','此待辦沒有回報。')}</p>}{rows?.map(row=><article className="k-card" key={row.id}><h2>{row.reason}</h2><p>{row.status} · {t('Assigned owner','指派負責人')}: {row.assignedTo??t('Unassigned','未指派')}</p><time dateTime={row.createdAt}>{row.createdAt}</time>{row.reviewReason&&<p>{row.reviewReason}</p>}{opsMode?<>{['assign','requestRevision','resolve'].map(type=><button className="k-btn" key={type} disabled={locked||reason.trim().length<10} onClick={()=>void send(row,type)}>{type==='assign'?t('Assign to me','指派予我'):type==='resolve'?t('Resolve report','結束回報'):t('Request revised details','要求修訂內容')}</button>)}</>:row.status==='reviewed'&&<button className="k-btn" disabled={locked||reason.trim().length<10} onClick={()=>void send(row,'revise')}>{t('Submit revised report','提交修訂回報')}</button>}</article>)}{cursor&&<button className="k-btn" disabled={locked} onClick={()=>void load(cursor!)}>{t('Next reports','下一頁回報')}</button>}</>}</section>;
}
