import type {TripSnapshot,TripCommand} from '../contracts/trips';
const database='kinnso_account_cache_v1';
type Draft={ownerId:string;tripId:string;baseRevision:number;requestId:string;command:TripCommand};
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(database,2);r.onupgradeneeded=()=>{for(const name of ['snapshots','drafts','identity'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('LOCAL_STORAGE_UNAVAILABLE'))})}
export async function synchronizeAccountCache(ownerId:string){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['identity','snapshots','drafts'],'readwrite'),identity=tx.objectStore('identity'),r=identity.get('actor');r.onsuccess=()=>{if(r.result?.ownerId!==ownerId){tx.objectStore('snapshots').clear();tx.objectStore('drafts').clear();identity.put({key:'actor',ownerId})}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
async function write(store:string,value:unknown){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
async function read<T>(store:string,key:string):Promise<T|null>{const db=await open();try{return await new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}finally{db.close()}}
export async function saveLocalSnapshot(ownerId:string,snapshot:TripSnapshot){await write('snapshots',{key:ownerId+':'+snapshot.id,ownerId,snapshot})}
export async function readLocalSnapshot(ownerId:string,tripId:string){const value=await read<{ownerId:string;snapshot:TripSnapshot}>('snapshots',ownerId+':'+tripId);return value?.ownerId===ownerId?value.snapshot:null}
export async function saveLocalDraft(ownerId:string,tripId:string,baseRevision:number,command:TripCommand,requestId:string){await write('drafts',{key:ownerId+':'+tripId,ownerId,tripId,baseRevision,command,requestId})}
export async function readLocalDraft(ownerId:string,tripId:string){const value=await read<Draft>('drafts',ownerId+':'+tripId);return value?.ownerId===ownerId?value:null}
export async function clearLocalDraft(ownerId:string,tripId:string){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').delete(ownerId+':'+tripId);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
export async function clearAccountCaches(){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['snapshots','drafts'],'readwrite');tx.objectStore('snapshots').clear();tx.objectStore('drafts').clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
