import type {TripSnapshot,TripCommand} from '../contracts/trips';
const database='kinnso_account_cache_v1';
type Draft={ownerId:string;tripId:string;baseRevision:number;requestId:string;command:TripCommand};
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(database,2);r.onupgradeneeded=()=>{for(const name of ['snapshots','drafts','identity'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('LOCAL_STORAGE_UNAVAILABLE'))})}
const accountEvent='kinnso:account-invalidated',channelName='kinnso-account-lifecycle';
export function invalidateAccountViews(ownerId:string|null){window.dispatchEvent(new CustomEvent(accountEvent,{detail:{ownerId}}));if(typeof BroadcastChannel!=='undefined'){const channel=new BroadcastChannel(channelName);channel.postMessage({ownerId});channel.close()}}
export function subscribeAccountInvalidation(callback:(ownerId:string|null)=>void){const handler=(event:Event)=>callback((event as CustomEvent<{ownerId:string|null}>).detail.ownerId);window.addEventListener(accountEvent,handler);const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel(channelName):null;if(channel)channel.onmessage=event=>{if(event.data?.ownerId===null||typeof event.data?.ownerId==='string')callback(event.data.ownerId)};return()=>{window.removeEventListener(accountEvent,handler);channel?.close()}}
export async function synchronizeAccountCache(ownerId:string){const db=await open();let changed=false;try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['identity','snapshots','drafts'],'readwrite'),identity=tx.objectStore('identity'),r=identity.get('actor');r.onsuccess=()=>{if(r.result?.ownerId!==ownerId){changed=!!r.result?.ownerId;tx.objectStore('snapshots').clear();tx.objectStore('drafts').clear();identity.put({key:'actor',ownerId})}};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}if(changed)invalidateAccountViews(ownerId)}
async function write(store:string,value:{key:string;ownerId:string;requestId?:string;[name:string]:unknown},allowReplace=false){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction([store,'identity'],'readwrite');let reason='LOCAL_STORAGE_UNAVAILABLE';const identity=tx.objectStore('identity').get('actor');identity.onsuccess=()=>{if(identity.result?.ownerId!==value.ownerId){reason='CACHE_ACCOUNT_CHANGED';tx.abort();return}const target=tx.objectStore(store);if(store==='drafts'){const old=target.get(value.key);old.onsuccess=()=>{if(old.result&&old.result.requestId!==value.requestId&&!allowReplace){reason='PENDING_DRAFT';tx.abort();return}target.put(value)}}else target.put(value)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(new Error(reason));tx.onabort=()=>reject(new Error(reason))})}finally{db.close()}}
async function read<T>(store:string,key:string,ownerId:string):Promise<T|null>{const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction([store,'identity']),identity=tx.objectStore('identity').get('actor');identity.onsuccess=()=>{if(identity.result?.ownerId!==ownerId){resolve(null);return}const r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)};identity.onerror=()=>reject(identity.error)})}finally{db.close()}}
export async function saveLocalSnapshot(ownerId:string,snapshot:TripSnapshot){await write('snapshots',{key:ownerId+':'+snapshot.id,ownerId,snapshot})}
export async function readLocalSnapshot(ownerId:string,tripId:string){const value=await read<{ownerId:string;snapshot:TripSnapshot}>('snapshots',ownerId+':'+tripId,ownerId);return value?.ownerId===ownerId?value.snapshot:null}
export async function saveLocalDraft(ownerId:string,tripId:string,baseRevision:number,command:TripCommand,requestId:string,allowReplace=false){await write('drafts',{key:ownerId+':'+tripId,ownerId,tripId,baseRevision,command,requestId},allowReplace)}
export async function readLocalDraft(ownerId:string,tripId:string){const value=await read<Draft>('drafts',ownerId+':'+tripId,ownerId);return value?.ownerId===ownerId?value:null}
export async function clearLocalDraft(ownerId:string,tripId:string,requestId:string){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite'),store=tx.objectStore('drafts'),key=ownerId+':'+tripId,r=store.get(key);r.onsuccess=()=>{if(r.result?.requestId===requestId)store.delete(key)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
export async function clearAccountCaches(){const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['snapshots','drafts','identity'],'readwrite');for(const name of ['snapshots','drafts','identity'])tx.objectStore(name).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
