import {test,expect,type Page} from '@playwright/test';import {loadEnvFile} from 'node:process';import {randomUUID} from 'node:crypto';import {createClient} from '@supabase/supabase-js';import {verifyTestTarget} from '../../scripts/verify-test-target.mjs';
loadEnvFile('.env.test');verifyTestTarget();const admin=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);const ids:string[]=[];
let a:Awaited<ReturnType<typeof actor>>,b:typeof a,creator:typeof a,summaryId:string,guideId:string;
async function actor(author=false){const email=`synthetic-u01-${randomUUID()}@example.test`,password=`U01!${randomUUID()}`,result=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(result.error).toBeNull();const id=result.data.user!.id;ids.push(id);if(author)expect((await admin.from('creators').update({status:'active',display_name:'Synthetic browser author'}).eq('id',id)).error).toBeNull();const client=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_ANON_KEY!);expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();return{id,email,password,client}}
async function guide(title:string){const result=await creator.client.from('guides').insert({creator_id:creator.id,creator_name:'Synthetic browser author',creator_handle:'synthetic',slug:'synthetic-'+randomUUID(),title,summary:'Summary is not an itinerary',cover_url:'',city:'Kyoto',status:'published',published_at:new Date().toISOString()}).select('id').single();expect(result.error).toBeNull();return result.data!.id}
test.beforeAll(async()=>{a=await actor();b=await actor();creator=await actor(true);summaryId=await guide('Synthetic summary only');guideId=await guide('Synthetic authored itinerary');expect((await creator.client.rpc('publish_guide_version',{p_guide_id:guideId,p_expected_version:0,p_request_id:randomUUID(),p_content:{days:[{offset:0,title:'Authored day',stops:[{title:'Authored source stop',description:'Public authored description',placeId:null,startMinuteOfDay:600,durationMinutes:30}]}]}})).error).toBeNull()});
test.afterAll(async()=>{for(const id of ids)expect((await admin.auth.admin.deleteUser(id)).error).toBeNull()});
async function signIn(page:Page){await page.getByLabel('Email').fill(a.email);await page.getByLabel('Password').fill(a.password);await page.getByRole('button',{name:'Sign in',exact:true}).click()}
test('anonymous bookmark returns once; summary never offers invented itinerary',async({page})=>{test.setTimeout(90000);await page.goto('/en/g/'+summaryId);await expect(page.getByText('This is a summary guide. It has no structured itinerary to apply.')).toBeVisible({timeout:15000});await expect(page.getByRole('button',{name:'Apply published itinerary',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Bookmark guide',exact:true}).click();await page.waitForURL('**/sign-in?*');await signIn(page);await expect(page.getByRole('button',{name:'Remove bookmark',exact:true})).toBeVisible({timeout:20000});await page.reload();await expect(page.getByRole('button',{name:'Remove bookmark',exact:true})).toBeVisible();const saved=await a.client.from('guide_saves').select('id').eq('guide_id',summaryId);expect(saved.data).toHaveLength(1);expect((await b.client.from('guide_saves').select('id').eq('guide_id',summaryId)).data).toHaveLength(0)});
test('guest edits import once, original stays, server adoption has real source, second context conflicts without losing input',async({page,browser})=>{test.setTimeout(150000);await page.goto('/en/g/'+guideId);await page.getByRole('button',{name:'Plan as a device-only draft',exact:true}).click();await page.getByLabel('Draft stop title',{exact:true}).fill('Personal device stop');await page.getByLabel('Draft private note',{exact:true}).fill('Synthetic private draft');await page.getByRole('button',{name:'Save device draft',exact:true}).click();await expect(page.getByTestId('guest-save-state')).toContainText('It is not synced to an account.');await page.getByRole('link',{name:'Sign in to review import',exact:true}).click();await signIn(page);await page.waitForURL('**/en/trips');await page.getByRole('button',{name:'Preview device-only drafts',exact:true}).click();await page.getByRole('button',{name:'Synthetic authored itinerary',exact:true}).click();const imported=page.waitForResponse(r=>r.url().endsWith('/api/trips/import')&&r.request().method()==='POST');await page.getByRole('button',{name:'Confirm import to this account',exact:true}).click();const first=(await (await imported).json()).data;expect(first.days[0].stops[0].source).toBeNull();const replay=page.waitForResponse(r=>r.url().endsWith('/api/trips/import')&&r.request().method()==='POST');await page.getByRole('button',{name:'Confirm import to this account',exact:true}).click();expect((await (await replay).json()).data.id).toBe(first.id);
 const retained=await page.evaluate(()=>new Promise<number>((resolve,reject)=>{const request=indexedDB.open('kinnso_guest_drafts_v1');request.onsuccess=()=>{const db=request.result,r=db.transaction('trips').objectStore('trips').count();r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>reject(r.error)}}));expect(retained).toBe(1);
 await page.goto('/en/g/'+guideId);await page.getByLabel('Apply to a trip',{exact:true}).selectOption(first.id);await page.getByRole('button',{name:'Apply published itinerary',exact:true}).click();await page.waitForURL('**/en/trips/'+first.id);await expect(page.getByLabel('Private note',{exact:true}).first()).toHaveValue('Synthetic private draft');const snapshot=(await a.client.rpc('get_trip_snapshot',{p_trip_id:first.id})).data;expect(snapshot.days[1].stops[0].source.guideVersion).toBe(1);expect((await b.client.rpc('get_trip_snapshot',{p_trip_id:first.id})).error?.message).toContain('trip_not_found');
 const context=await browser.newContext(),other=await context.newPage();await other.goto('/en/sign-in?next='+encodeURIComponent('/en/trips/'+first.id));await signIn(other);await expect(other.getByLabel('Private note',{exact:true}).first()).toHaveValue('Synthetic private draft');await page.getByLabel('Private note',{exact:true}).first().fill('First context committed');await page.getByRole('button',{name:'Save stop',exact:true}).first().click();await expect(page.getByTestId('trip-save-state')).toContainText('Saved to your account');await other.getByLabel('Private note',{exact:true}).first().fill('Second context uncommitted');await other.getByRole('button',{name:'Save stop',exact:true}).first().click();await expect(other.getByTestId('trip-save-state')).toContainText('Conflict.');await expect(other.getByLabel('Private note',{exact:true}).first()).toHaveValue('Second context uncommitted');expect((await a.client.rpc('get_trip_snapshot',{p_trip_id:first.id})).data.days[0].stops[0].travellerNote).toBe('First context committed');await context.close();
 await page.context().setOffline(true);await page.getByLabel('Private note',{exact:true}).first().fill('Synthetic offline draft');await page.getByRole('button',{name:'Save stop',exact:true}).first().click();await expect(page.getByTestId('trip-save-state')).toContainText('local draft is not synced');await page.context().setOffline(false);await page.getByRole('button',{name:'Retry local draft with revision check',exact:true}).click();await expect(page.getByTestId('trip-save-state')).toContainText('Saved to your account');expect((await a.client.rpc('get_trip_snapshot',{p_trip_id:first.id})).data.days[0].stops[0].travellerNote).toBe('Synthetic offline draft');
});
