import {test,expect,type Page} from '@playwright/test';
import {loadEnvFile} from 'node:process';import {randomUUID} from 'node:crypto';import {createClient} from '@supabase/supabase-js';import {verifyTestTarget} from '../../scripts/verify-test-target.mjs';
loadEnvFile('.env.test');verifyTestTarget();
const admin=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);const ids:string[]=[];
async function fixture(){const email=`synthetic-recovery-${randomUUID()}@example.test`,password=`UI!${randomUUID()}`;const user=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(user.error).toBeNull();ids.push(user.data.user!.id);const client=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_ANON_KEY!);expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();return {id:user.data.user!.id,email,password,client}}
async function createTrip(a:Awaited<ReturnType<typeof fixture>>){let t=(await a.client.rpc('create_trip_v2',{p_request_id:randomUUID(),p_payload:{title:'Synthetic private recovery',timezone:'UTC'}})).data;const day=randomUUID();t=(await a.client.rpc('apply_trip_command',{p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'addDay',id:day,offset:0,title:'Day'}})).data;for(let position=0;position<2;position++)t=(await a.client.rpc('apply_trip_command',{p_trip_id:t.id,p_expected_revision:t.revision,p_request_id:randomUUID(),p_command:{type:'addStop',id:randomUUID(),dayId:day,position,input:{title:'Stop '+position,placeId:null,travellerNote:'Private account A '+position,startMinuteOfDay:null,durationMinutes:null}}})).data;return t}
async function login(page:Page,a:Awaited<ReturnType<typeof fixture>>,next:string){await page.goto('/en/sign-in?next='+encodeURIComponent(next));await page.getByLabel('Email').fill(a.email);await page.getByLabel('Password').fill(a.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**'+next);await expect(page.locator('[data-ready="true"]')).toBeVisible()}
async function draft(page:Page,id:string){return page.evaluate(id=>new Promise<Record<string,unknown>|null>((resolve,reject)=>{const r=indexedDB.open('kinnso_account_cache_v1');r.onsuccess=()=>{const db=r.result,q=db.transaction('drafts').objectStore('drafts').getAll();q.onsuccess=()=>{resolve(q.result.find(row=>row.tripId===id)??null);db.close()};q.onerror=()=>reject(q.error)}}),id)}
test.afterAll(async()=>{for(const id of ids)expect((await admin.auth.admin.deleteUser(id)).error).toBeNull()});
test('an unresolved offline edit cannot be replaced by another command',async({page})=>{test.setTimeout(90000);const a=await fixture(),t=await createTrip(a);await login(page,a,'/en/trips/'+t.id);await expect(page.getByLabel('Private note',{exact:true}).first()).toHaveValue('Private account A 0');await page.context().setOffline(true);
 await page.getByLabel('Private note',{exact:true}).first().fill('Recovered offline note A');await page.getByRole('button',{name:'Save stop',exact:true}).first().click();await expect(page.getByTestId('trip-save-state')).toContainText('not synced');const original=await draft(page,t.id);
 await page.getByLabel('Private note',{exact:true}).nth(1).fill('Unconfirmed new note B');await page.getByRole('button',{name:'Save stop',exact:true}).nth(1).click();await expect.poll(()=>draft(page,t.id)).toEqual(original);await expect(page.getByTestId('trip-save-state')).toContainText('pending edit');
 await page.context().setOffline(false);await page.reload();await page.getByRole('button',{name:'Retry local draft with revision check',exact:true}).click();await expect(page.getByTestId('trip-save-state')).toContainText('Saved to your account');expect((await a.client.rpc('get_trip_snapshot',{p_trip_id:t.id})).data.days[0].stops[0].travellerNote).toBe('Recovered offline note A');
});
test('guide trip choices and saved interests clear across tabs, including a delayed old bookmark response',async({page,context})=>{
 test.setTimeout(120000);const a=await fixture(),b=await fixture(),trip=await createTrip(a);
 const source=await admin.from('guides').insert({creator_id:a.id,creator_name:'Synthetic privacy source',creator_handle:'synthetic',slug:'synthetic-'+randomUUID(),title:'Synthetic account A interest',summary:'Private interest fixture',cover_url:'',city:'Kyoto',status:'published',published_at:new Date().toISOString()}).select('id').single();expect(source.error).toBeNull();const guideId=source.data!.id;
 expect((await a.client.rpc('kinnso_bookmark',{p_guide_id:guideId,p_desired_state:true,p_request_id:randomUUID()})).error).toBeNull();
 expect((await admin.from('creators').update({status:'active'}).eq('id',a.id)).error).toBeNull();
 expect((await a.client.rpc('publish_guide_version',{p_guide_id:guideId,p_expected_version:0,p_request_id:randomUUID(),p_content:{days:[{offset:0,title:'Synthetic day',stops:[{title:'Public source',description:'Authored fixture',placeId:null,startMinuteOfDay:null,durationMinutes:null}]}]}})).error).toBeNull();
 await login(page,a,'/en/trips');const guide=await context.newPage(),saved=await context.newPage(),late=await context.newPage();
 await guide.goto('/en/g/'+guideId);await expect(guide.getByRole('button',{name:'Remove bookmark',exact:true})).toBeVisible();await expect(guide.getByLabel('Apply to a trip',{exact:true}).locator('option')).toContainText(['Choose an existing trip',trip.title]);
 await saved.goto('/en/saved');await expect(saved.getByRole('link',{name:'Synthetic account A interest',exact:true})).toBeVisible();
 let release!:()=>void,fetched!:()=>void,delivered!:()=>void;const held=new Promise<void>(r=>{release=r}),ready=new Promise<void>(r=>{fetched=r}),delivery=new Promise<void>(r=>{delivered=r});
 await late.route('**/api/bookmarks',async route=>{try{const response=await route.fetch();fetched();await held;await route.fulfill({response})}finally{delivered()}});await late.goto('/en/saved');await ready;
 try{await page.goto('/en/me');await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/en/sign-in');
 await expect(guide.getByLabel('Apply to a trip',{exact:true})).toHaveCount(0);await expect(guide.getByRole('button',{name:'Remove bookmark',exact:true})).toHaveCount(0);await expect(saved.getByRole('link',{name:'Synthetic account A interest',exact:true})).toHaveCount(0);
 await login(page,b,'/en/trips');release();await delivery;await late.unroute('**/api/bookmarks');await expect(late.getByRole('link',{name:'Synthetic account A interest',exact:true})).toHaveCount(0);
 await guide.reload();await expect(guide.getByLabel('Apply to a trip',{exact:true}).locator('option')).toHaveCount(1);await expect(guide.getByRole('button',{name:'Bookmark guide',exact:true})).toBeVisible();
 }finally{release();await Promise.all([guide.close(),saved.close(),late.close()])}
});
test('logout and account switch invalidate another tab and reject an outstanding account response',async({page,context})=>{test.setTimeout(90000);const a=await fixture(),b=await fixture(),t=await createTrip(a);await login(page,a,'/en/trips/'+t.id);const other=await context.newPage();await other.goto('/en/trips/'+t.id);await expect(other.getByLabel('Private note',{exact:true}).first()).toHaveValue('Private account A 0');let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve});let fetched!:()=>void;const ready=new Promise<void>(resolve=>{fetched=resolve});
 let delivered!:()=>void;const delivery=new Promise<void>(resolve=>{delivered=resolve});await other.route('**/api/trips/'+t.id,async route=>{try{const response=await route.fetch();fetched();await held;await route.fulfill({response})}finally{delivered()}});await other.getByRole('button',{name:'Load current version',exact:true}).click();await ready;
 try{await page.goto('/en/me');await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/en/sign-in');await expect(other.getByLabel('Private note',{exact:true})).toHaveCount(0);await login(page,b,'/en/trips');release();await delivery;await other.unroute('**/api/trips/'+t.id);await expect(other.getByLabel('Private note',{exact:true})).toHaveCount(0);await expect(other.getByRole('button',{name:'Download private trip for offline reading',exact:true})).toHaveCount(0);
 const count=await page.evaluate(()=>new Promise<number>((resolve,reject)=>{const r=indexedDB.open('kinnso_account_cache_v1');r.onsuccess=()=>{const db=r.result,q=db.transaction('snapshots').objectStore('snapshots').count();q.onsuccess=()=>{resolve(q.result);db.close()};q.onerror=()=>reject(q.error)}}));expect(count).toBe(0);
 }finally{release();await other.close()}
});
