import {test,expect,type Page} from '@playwright/test';import {loadEnvFile} from 'node:process';import {randomUUID} from 'node:crypto';import {createClient} from '@supabase/supabase-js';import {verifyTestTarget} from '../../scripts/verify-test-target.mjs';
loadEnvFile('.env.test');verifyTestTarget();const admin=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}}),ids:string[]=[];
test.use({actionTimeout:15000});
test.afterEach(async()=>{for(const id of ids.splice(0))expect((await admin.auth.admin.deleteUser(id)).error).toBeNull()});
for(const locale of ['en','zh-HK'])test('home retry, approved cover, original text and anonymous status '+locale,async({page})=>{
 const covered={id:randomUUID(),slug:'synthetic-covered',title:'Synthetic original English author text',city:'Kyoto',summary:'Original authored summary',creator:'Synthetic local author',creatorHandle:'synthetic',publishedAt:null,cover:'https://cdn.kinnso.ai/synthetic-local-test-cover.svg'},bare={...covered,id:randomUUID(),slug:'synthetic-no-cover',title:'Synthetic readable route without a cover',cover:null};let requests=0;
 await page.route('**/api/catalog',route=>{requests++;return route.fulfill({status:requests===1?503:200,contentType:'application/json',body:JSON.stringify(requests===1?{status:'error',code:'UNAVAILABLE'}:{status:'ready',items:[covered,bare],hasMore:false,query:{page:1,pageSize:12,q:'',city:''}})});});
 await page.route('https://cdn.kinnso.ai/synthetic-local-test-cover.svg',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="400" height="240"><rect width="400" height="240" fill="#e7eadf"/></svg>'}));
 await page.goto('/'+locale);await expect(page.locator('.k-mode')).toContainText(locale==='en'?'Browsing published guides':'瀏覽已發布攻略');
 const retry=page.getByRole('button',{name:locale==='en'?'Retry published guides':'重試已發布攻略',exact:true});await expect(retry).toBeVisible();await retry.click();await expect(page.getByRole('link',{name:covered.title,exact:true})).toBeVisible();expect(requests).toBe(2);
 const cards=page.locator('.k-card-grid.home article');await expect(cards).toHaveCount(2);await expect(cards.first().locator('img')).toHaveAttribute('src',covered.cover);await expect(cards.nth(1).locator('img')).toHaveCount(0);await expect(cards.nth(1)).toContainText(bare.creator);await expect(cards.nth(1)).toContainText('Kyoto');
 await expect(page.getByRole('link',{name:locale==='en'?'Kyoto':'京都',exact:true})).toHaveAttribute('href','/'+locale+'/explore?q=Kyoto');await expect(page.getByRole('link',{name:locale==='en'?'Hong Kong':'香港',exact:true})).toHaveAttribute('href','/'+locale+'/explore?q=Hong%20Kong');
 await expect(page.locator('.k-record-banner .k-eyebrow')).toHaveText(locale==='en'?'KEEP THE LITTLE THINGS.':'記住旅途的小事。');await expect(page.getByText(locale==='en'?'Guide text is shown as published by its author.':'攻略原文依作者發布內容顯示。',{exact:true})).toBeVisible();
 await page.setViewportSize({width:320,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);await page.screenshot({path:test.info().outputPath('home-320.png'),fullPage:true});
});
async function login(page:Page,email:string,password:string,next:string){await page.goto('/en/sign-in?next='+encodeURIComponent(next));await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**'+next);}
test('synthetic creator publishes structured revisions; new traveller explicitly imports and reads another device after withdrawal',async({page,browser})=>{
 test.setTimeout(120000);const email=`synthetic-content-author-${randomUUID()}@example.test`,password=`Author!${randomUUID()}`,title='Synthetic structured U01 U03 '+randomUUID();
 const actor=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(actor.error).toBeNull();ids.push(actor.data.user!.id);await login(page,email,password,'/en/studio');
 const confirm=page.getByRole('button',{name:'Confirm creator profile',exact:true});await expect(confirm).toBeVisible();await page.getByLabel('Bio',{exact:true}).fill('Synthetic isolated manual author');await page.getByLabel('I have reviewed this profile and confirm publication.',{exact:true}).check();await confirm.click();await expect(page.getByRole('link',{name:'Create guide',exact:true})).toBeVisible();await page.getByRole('link',{name:'Create guide',exact:true}).click();
 await page.getByLabel('Guide title',{exact:true}).fill(title);await page.getByLabel('Destination',{exact:true}).fill('Kyoto');await page.getByLabel('Summary',{exact:true}).fill('Synthetic authored directions, never inferred from a summary');await page.getByLabel('Day title',{exact:true}).fill('Synthetic authored first day');await page.getByLabel('Stop title',{exact:true}).fill('Synthetic original stop');await page.getByRole('textbox',{name:'Public description',exact:true}).fill('Original public instructions');await page.getByLabel('Start time (HH:mm, optional)',{exact:true}).fill('09:30');
 await expect(page.getByRole('button',{name:'Save draft',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect(page.getByTestId('creator-editor').getByRole('status')).toHaveText('Draft saved.');const guideId=page.url().split('/').at(-2)!;const first=(await (await page.request.get('/api/creator/guides/'+guideId)).json()).data;
 await page.getByLabel('Stop title',{exact:true}).fill('Synthetic revised authored stop');await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect(page.getByTestId('creator-editor').getByRole('status')).toHaveText('Draft saved.');const revision=(await (await page.request.get('/api/creator/guides/'+guideId)).json()).data;expect(revision.revision).toBeGreaterThan(first.revision);
 await page.getByRole('button',{name:'Publish structured version',exact:true}).click();await expect(page.getByTestId('creator-editor').getByRole('status')).toContainText('Version published.');const source=(await (await page.request.get('/api/guides/'+guideId)).json()).data;expect(source.kind).toBe('itinerary');expect(source.version).toBe(1);expect(source.days[0].stops[0].title).toBe('Synthetic revised authored stop');expect(source.days[0].stops[0].startMinuteOfDay).toBe(570);
 const traveller=await browser.newContext({baseURL:'http://127.0.0.1:3495'}),guest=await traveller.newPage(),travellerEmail=`synthetic-content-traveller-${randomUUID()}@example.test`,travellerPassword=`Traveller!${randomUUID()}`;let other:Awaited<ReturnType<typeof browser.newContext>>|undefined;
 try{
  await guest.goto('http://127.0.0.1:3495/en/explore?q='+encodeURIComponent(title));await guest.getByRole('link',{name:title,exact:true}).click();await guest.waitForURL('**/en/g/'+guideId);await expect(guest.getByRole('heading',{name:'Synthetic revised authored stop',exact:true})).toBeVisible();await guest.getByRole('button',{name:'Plan as a device-only draft',exact:true}).click();await expect(guest.getByTestId('guest-save-state')).toContainText('Device draft saved.');await guest.getByRole('textbox',{name:'Draft private note',exact:true}).fill('Synthetic traveller private note');await guest.getByRole('button',{name:'Save device draft',exact:true}).click();await expect(guest.getByTestId('guest-save-state')).toContainText('Device draft saved.');
  await guest.getByRole('link',{name:'Sign in to review import',exact:true}).click();await expect(guest).toHaveURL(/\/en\/sign-in\?next=/);await guest.getByRole('link',{name:'Create an account',exact:true}).click();await expect(guest.getByRole('heading',{name:'Create your Kinnso account',exact:true})).toBeVisible();await guest.getByLabel('Email',{exact:true}).fill(travellerEmail);await guest.getByLabel('New password',{exact:true}).fill(travellerPassword);await guest.getByLabel('Confirm password',{exact:true}).fill(travellerPassword);const validity=await guest.locator('form').evaluate(form=>Array.from(form.querySelectorAll('input')).map(input=>({name:input.name,type:input.type,length:input.value.length,valid:input.validity.valid,valueMissing:input.validity.valueMissing,typeMismatch:input.validity.typeMismatch,tooShort:input.validity.tooShort})));expect(validity.filter(input=>!input.valid)).toEqual([]);await expect(guest.getByLabel('Email',{exact:true})).toHaveValue(travellerEmail);await guest.getByRole('button',{name:'Create account',exact:true}).click();await expect(guest).toHaveURL('http://127.0.0.1:3495/en/trips',{timeout:15000});const owner=(await (await guest.request.get('/api/session')).json()).data;ids.push(owner.id);expect((await (await guest.request.get('/api/trips')).json()).data.items).toEqual([]);
  await guest.getByRole('button',{name:'Preview device-only drafts',exact:true}).click();await guest.getByRole('button',{name:title,exact:true}).click();await expect(guest.getByRole('button',{name:'Confirm import to this account',exact:true})).toBeEnabled();await guest.getByRole('button',{name:'Confirm import to this account',exact:true}).click();await expect(guest.getByRole('status',{name:'Local import status',exact:true})).toContainText('Trip imported to your account.');const accountTrips=(await (await guest.request.get('/api/trips')).json()).data.items;expect(accountTrips).toHaveLength(1);const tripId=accountTrips[0].id;
  const replayReply=guest.waitForResponse(response=>new URL(response.url()).pathname==='/api/trips/import'&&response.request().method()==='POST');await guest.getByRole('button',{name:'Confirm import to this account',exact:true}).click();const replay=await replayReply;expect(replay.ok()).toBe(true);expect((await replay.json()).data.id).toBe(tripId);await expect(guest.getByRole('status',{name:'Local import status',exact:true})).toContainText('Trip imported');expect((await (await guest.request.get('/api/trips')).json()).data.items).toHaveLength(1);
  await page.getByRole('button',{name:'Withdraw adoption',exact:true}).click();await expect(page.getByTestId('creator-editor').getByRole('status')).toContainText('withdrawn');const withdrawn=await guest.request.get('/api/guides/'+guideId);expect(withdrawn.status()).toBe(200);expect((await withdrawn.json()).data.kind).toBe('summary');
  // UI withdrawal closes new adoption; full unpublication is a separate, scoped local fixture transition.
  const unpublished=await admin.from('guides').update({status:'draft'}).eq('id',guideId).eq('creator_id',actor.data.user!.id).select('id').single();expect(unpublished.error).toBeNull();expect(unpublished.data!.id).toBe(guideId);expect((await guest.request.get('/api/guides/'+guideId)).status()).toBe(404);await guest.close();
  other=await browser.newContext({baseURL:'http://127.0.0.1:3495'});const reopened=await other.newPage();await reopened.goto('http://127.0.0.1:3495/en/sign-in?next='+encodeURIComponent('/en/trips/'+tripId));await reopened.getByLabel('Email',{exact:true}).fill(travellerEmail);await reopened.getByLabel('Password',{exact:true}).fill(travellerPassword);await reopened.getByRole('button',{name:'Sign in',exact:true}).click();await reopened.waitForURL('**/en/trips/'+tripId);await expect(reopened.getByRole('textbox',{name:'Private note',exact:true}).first()).toHaveValue('Synthetic traveller private note');const persisted=(await (await reopened.request.get('/api/trips/'+tripId)).json()).data;expect((await (await reopened.request.get('/api/session')).json()).data.id).toBe(owner.id);const ownership=await admin.from('trips').select('owner_user_id').eq('id',tripId).single();expect(ownership.error).toBeNull();expect(ownership.data!.owner_user_id).toBe(owner.id);expect(persisted.days[0].stops[0].title).toBe('Synthetic revised authored stop');expect(persisted.days[0].stops[0].travellerNote).toBe('Synthetic traveller private note');
  // This is a fresh browser context with no device draft database to import.
  expect(await reopened.evaluate(()=>indexedDB.databases().then(rows=>rows.some(row=>row.name==='kinnso_guest_drafts_v1')))).toBe(false);
 }catch(error){await test.info().attach('synthetic-traveller-visible-state',{body:guest.isClosed()?'closed':guest.url()+'\n'+await guest.locator('body').innerText(),contentType:'text/plain'});throw error}finally{await other?.close().catch(()=>{});await traveller.close().catch(()=>{})}
});
