import {test,expect} from '@playwright/test';import {loadEnvFile} from 'node:process';import {randomUUID} from 'node:crypto';import {createClient} from '@supabase/supabase-js';import {verifyTestTarget} from '../../scripts/verify-test-target.mjs';
loadEnvFile('.env.test');verifyTestTarget();const admin=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);
let email:string,password:string,userId:string,tripId:string;
test.beforeAll(async()=>{email=`synthetic-u02-${randomUUID()}@example.test`;password=`U02!${randomUUID()}`;const user=await admin.auth.admin.createUser({email,password,email_confirm:true});expect(user.error).toBeNull();userId=user.data.user!.id;const client=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_ANON_KEY!);expect((await client.auth.signInWithPassword({email,password})).error).toBeNull();let trip=(await client.rpc('create_trip_v2',{p_request_id:randomUUID(),p_payload:{title:'Synthetic travel sharing',timezone:'Asia/Tokyo',startDate:null}})).data;tripId=trip.id;const day=randomUUID();trip=(await client.rpc('apply_trip_command',{p_trip_id:tripId,p_expected_revision:1,p_request_id:randomUUID(),p_command:{type:'addDay',id:day,offset:0,title:'First day'}})).data;expect((await client.rpc('apply_trip_command',{p_trip_id:tripId,p_expected_revision:trip.revision,p_request_id:randomUUID(),p_command:{type:'addStop',id:randomUUID(),dayId:day,position:0,input:{title:'Selected public place',placeId:null,travellerNote:'PRIVATE U02 leak sentinel',startMinuteOfDay:600,durationMinutes:60}}})).error).toBeNull()});
test.afterAll(async()=>{if(userId)expect((await admin.auth.admin.deleteUser(userId)).error).toBeNull()});
test('private photo persists, anonymous readonly share excludes notes and media stops after revoke',async({page,browser})=>{
 test.setTimeout(120000);await page.goto('/en/sign-in?next='+encodeURIComponent('/en/trips/'+tripId));await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByLabel('Private note',{exact:true})).toHaveValue('PRIVATE U02 leak sentinel',{timeout:15000});
 const dataUrl=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=16;canvas.height=16;canvas.getContext('2d')!.fillRect(0,0,16,16);return canvas.toDataURL('image/png')});const bytes=Buffer.from(dataUrl.split(',')[1],'base64');await page.getByLabel('Photo',{exact:true}).setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:bytes});await page.getByRole('button',{name:'Upload private photo',exact:true}).click();await expect(page.getByAltText('Private trip photo')).toBeVisible({timeout:45000});
 await page.reload();await expect(page.getByAltText('Private trip photo')).toBeVisible({timeout:15000});await page.getByRole('checkbox',{name:'Selected public place',exact:true}).check();await page.getByRole('checkbox',{name:/Private photo/}).check();await page.getByRole('button',{name:'Create read-only link',exact:true}).click();const field=page.getByLabel('Share link',{exact:true});await expect(field).toBeVisible();const url=await field.inputValue();
 const friend=await browser.newContext();const viewer=await friend.newPage();const response=await viewer.goto(url);expect(response?.status()).toBe(200);await expect(viewer.getByText('Selected public place',{exact:true})).toBeVisible();await expect(viewer.getByText('PRIVATE U02 leak sentinel')).toHaveCount(0);const image=viewer.getByAltText('Owner-selected trip photograph');await expect(image).toBeVisible();const mediaUrl=await image.getAttribute('src');expect((await viewer.request.get(mediaUrl!)).status()).toBe(200);
 await page.reload();await expect(page.getByRole('button',{name:'Revoke existing link',exact:true})).toBeVisible({timeout:15000});const revoked=page.waitForResponse(r=>r.request().method()==='DELETE'&&r.url().includes('/api/shares/'));await page.getByRole('button',{name:'Revoke existing link',exact:true}).click();expect((await revoked).status()).toBe(200);expect((await viewer.request.get(url)).status()).toBe(404);expect((await viewer.request.get(mediaUrl!)).status()).toBe(404);await friend.close();
});
