import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {loadEnvFile} from 'node:process';
import {createClient} from '@supabase/supabase-js';
import {verifyTestTarget} from '../../scripts/verify-test-target.mjs';
loadEnvFile('.env.test');verifyTestTarget();
const boundedFetch:typeof fetch=(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(10_000)});
const admin=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false},global:{fetch:boundedFetch}});
const ok=async(p:PromiseLike<any>)=>{const r=await p;expect(r.error).toBeNull();return r.data;};
async function signIn(page:Page,actor:{email:string;password:string;id:string},path:string){
 page.setDefaultTimeout(15_000);await page.goto('/en/sign-in?next='+encodeURIComponent('/en/'+path));await page.getByLabel('Email',{exact:true}).fill(actor.email);await page.getByLabel('Password',{exact:true}).fill(actor.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/en/'+path);
 await expect.poll(async()=>{const r=await page.request.get('/api/session');return(await r.json()).data?.id;}).toBe(actor.id);
}
test('U03/U04 complete native merchant intake, authored collaboration, revision and recorded outcome',async({page,browser,baseURL},testInfo)=>{
 test.setTimeout(180_000);expect(new URL(baseURL!).origin).toBe('http://127.0.0.1:3495');
 const users:string[]=[],contexts:Awaited<ReturnType<typeof browser.newContext>>[]=[];let merchantId:string|undefined,applicationId:string|undefined,opsId:string|undefined,missionId:string|undefined,failed=false;
 async function actor(creator=false){const email=`synthetic-cm-${randomUUID()}@example.test`,password=`Synthetic!${randomUUID()}`;const user=(await ok(admin.auth.admin.createUser({email,password,email_confirm:true}))).user;users.push(user.id);if(creator)await ok(admin.from('creators').update({status:'active',display_name:'Synthetic original author'}).eq('id',user.id));return{id:user.id,email,password};}
 try{
  const owner=await actor(),operator=await actor(),creator=await actor(true);
  opsId=(await ok(admin.from('kinnso_ops_members').insert({user_id:operator.id,display_name:'Synthetic collaboration moderator',role:'moderator'}).select('id').single())).id;
  await signIn(page,owner,'merchant');await expect(page.getByRole('heading',{name:'Apply as a merchant',exact:true})).toBeVisible();
  await page.getByLabel('Company name',{exact:true}).fill('Synthetic collaboration cafe');await page.getByLabel('Contact name',{exact:true}).fill('Synthetic cafe owner');await page.getByLabel('Contact email',{exact:true}).fill(owner.email);await page.getByLabel('Website (HTTPS, optional)',{exact:true}).fill('https://example.test/cafe');await page.getByLabel('Collaboration proposal (optional)',{exact:true}).fill('Author an original local tasting route.');await page.getByLabel('I confirm these business and contact details are correct.',{exact:true}).check();
  const intakePayloads:unknown[]=[];let intakeAttempt=0;
  await page.route('**/api/merchant/application',async route=>{if(route.request().method()!=='POST')return route.continue();intakePayloads.push(route.request().postDataJSON());const response=await route.fetch();if(++intakeAttempt===1)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,code:'UNAVAILABLE',retryable:true})});return route.fulfill({response});});
  await page.getByRole('button',{name:'Submit merchant application',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same application',exact:true})).toBeVisible();await expect(page.getByLabel('Company name',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same application',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Application pending review'})).toBeVisible();expect(intakePayloads).toHaveLength(2);expect(intakePayloads[0]).toEqual(intakePayloads[1]);
  const applications=await ok(admin.from('merchant_applications').select('id,status').eq('user_id',owner.id));expect(applications).toHaveLength(1);applicationId=applications[0].id;
  const opsContext=await browser.newContext({baseURL});contexts.push(opsContext);const opsPage=await opsContext.newPage();await signIn(opsPage,operator,'ops/merchants');
  await opsPage.getByLabel('Pending merchant application',{exact:true}).selectOption(applicationId!);await opsPage.getByLabel('Decision reason',{exact:true}).fill('Synthetic reviewed business and contact details');await opsPage.getByRole('button',{name:'Approve application',exact:true}).click();await expect(opsPage.getByRole('status').filter({hasText:'Recorded decision: approved'})).toBeVisible();
  merchantId=(await ok(admin.from('merchant_profiles').select('id').eq('user_id',owner.id).single())).id;
  await page.unroute('**/api/merchant/application');await page.reload();await expect(page.getByLabel('Company',{exact:true})).toHaveValue(merchantId!);
  await page.getByLabel('Company introduction',{exact:true}).fill('Original neighbourhood tasting experiences');await page.getByLabel('City',{exact:true}).fill('Hong Kong');await page.getByRole('button',{name:'Save company profile',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Company profile saved.'})).toBeVisible();
  await page.getByLabel('Brief title',{exact:true}).fill('Synthetic neighbourhood tasting route');await page.getByLabel('Brief description',{exact:true}).fill('Create an original two-stop route and share your authored post for review.');await page.getByLabel('Coupon code',{exact:true}).fill('SYNTHETIC-CM');await page.getByLabel('Coupon URL',{exact:true}).fill('https://example.test/coupon');
  for(const label of ['Affiliate commission rate (%)','Platform commission rate (%)','Creator commission rate (%)'])await page.getByLabel(label,{exact:true}).fill('0');
  await page.getByLabel('Creator requirements, one per line',{exact:true}).fill('Create your own text and photos');await page.getByLabel('Expected deliverables, one per line',{exact:true}).fill('One published route with proof URL');
  await page.getByRole('button',{name:'Add milestone',exact:true}).click();await page.getByLabel('Milestone title',{exact:true}).fill('Original tasting route');await page.getByLabel('Milestone instructions',{exact:true}).fill('Submit a public HTTPS link to your original route.');await page.getByRole('button',{name:'Save promotion draft',exact:true}).click();await expect(page.getByRole('button',{name:'Publish saved draft',exact:true})).toBeVisible();
  missionId=(await ok(admin.from('missions').select('id,status').eq('merchant_profile_id',merchantId).single())).id;expect((await ok(admin.from('missions').select('status').eq('id',missionId).single())).status).toBe('draft');
  await page.getByRole('button',{name:'Publish saved draft',exact:true}).click();await expect(page.getByRole('button',{name:'Close new applications',exact:true})).toBeVisible();
  const creatorContext=await browser.newContext({baseURL});contexts.push(creatorContext);const creatorPage=await creatorContext.newPage();await signIn(creatorPage,creator,'studio/missions/'+missionId);
  await expect(creatorPage.getByRole('heading',{name:'Synthetic neighbourhood tasting route',exact:true})).toBeVisible();await creatorPage.getByLabel('Application note (optional)',{exact:true}).fill('I will author this route in English and Cantonese.');await creatorPage.getByLabel('I have read the collaboration requirements.',{exact:true}).check();await creatorPage.getByRole('button',{name:/^(Join collaboration|Send application)$/}).click();
  await expect.poll(async()=>(await ok(admin.from('mission_participants').select('status').eq('mission_id',missionId).eq('creator_id',creator.id).single())).status).toBe('applied');
  await page.getByRole('button',{name:'Reload promotion',exact:true}).click();await page.getByLabel('Application review feedback',{exact:true}).fill('Accepted: please follow the original route brief.');await page.getByRole('button',{name:'Approve application',exact:true}).click();await expect(page.getByRole('button',{name:'Approve application',exact:true})).toHaveCount(0);
  await creatorPage.getByRole('button',{name:'Refresh collaborations',exact:true}).click();await creatorPage.getByRole('button',{name:'Prepare evidence',exact:true}).click();await creatorPage.getByLabel('Evidence links (one HTTPS link per line)',{exact:true}).fill('https://example.test/original-route-v1');await creatorPage.getByLabel('Notes for reviewer',{exact:true}).fill('First original draft for review.');await creatorPage.getByRole('button',{name:'Submit evidence',exact:true}).click();await expect(creatorPage.getByRole('heading',{name:'Your evidence',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Reload promotion',exact:true}).click();await page.getByLabel('Deliverable review feedback',{exact:true}).fill('Please add opening hours to both stops.');await page.getByRole('button',{name:'Request revision',exact:true}).click();await expect(page.getByRole('button',{name:'Request revision',exact:true})).toHaveCount(0);
  // Closing new applications must preserve accepted creators' ability to finish.
  await page.getByRole('button',{name:'Close new applications',exact:true}).click();await expect.poll(async()=>(await ok(admin.from('missions').select('status').eq('id',missionId).single())).status).toBe('paused');
  await creatorPage.getByRole('button',{name:'Refresh collaborations',exact:true}).click();await expect(creatorPage.getByText('Please add opening hours to both stops.',{exact:false}).first()).toBeVisible();await creatorPage.getByRole('button',{name:'Edit and resubmit evidence',exact:true}).click();await creatorPage.getByLabel('Evidence links (one HTTPS link per line)',{exact:true}).fill('https://example.test/original-route-v2');await creatorPage.getByLabel('Notes for reviewer',{exact:true}).fill('Added hours and checked the original locations.');await creatorPage.getByRole('button',{name:'Submit evidence',exact:true}).click();await expect(creatorPage.getByRole('heading',{name:'Your evidence',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Reload promotion',exact:true}).click();await page.getByLabel('Deliverable review feedback',{exact:true}).fill('Verified original route and opening hours.');await page.getByRole('button',{name:'Approve deliverable',exact:true}).click();await expect(page.getByRole('button',{name:'Approve deliverable',exact:true})).toHaveCount(0);
  await creatorPage.getByRole('button',{name:'Refresh collaborations',exact:true}).click();await expect(creatorPage.getByText('Verified original route and opening hours.',{exact:false}).first()).toBeVisible();
  const participantId=(await ok(admin.from('mission_participants').select('id').eq('mission_id',missionId).eq('creator_id',creator.id).single())).id;
  const submissions=await ok(admin.from('mission_milestone_submissions').select('id,status,proof_urls').eq('mission_participant_id',participantId));expect(submissions).toHaveLength(1);expect(submissions[0].status).toBe('approved');expect(submissions[0].proof_urls).toEqual(['https://example.test/original-route-v2']);expect(await ok(admin.from('mission_settlements').select('id').eq('mission_id',missionId))).toHaveLength(0);
  await creatorPage.setViewportSize({width:320,height:800});await expect.poll(()=>creatorPage.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await testInfo.attach('creator-collaboration-320',{body:await creatorPage.screenshot({fullPage:true}),contentType:'image/png'});
  await creatorPage.goto('/zh-HK/studio/earnings');await expect(creatorPage.getByRole('heading',{name:'你的收益紀錄',exact:true})).toBeVisible();await expect(creatorPage.getByRole('heading',{name:'此分類暫未有紀錄。',exact:true})).toBeVisible();
  await page.setViewportSize({width:320,height:800});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await testInfo.attach('merchant-collaboration-320',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
 }catch(error){failed=true;throw error;}finally{
  const errors:string[]=[];const clean=async(label:string,fn:()=>PromiseLike<unknown>)=>{try{await fn();}catch{errors.push(label);}};
  for(const context of contexts)await clean('context',()=>context.close());if(applicationId)await clean('application',()=>ok(admin.from('merchant_applications').delete().eq('id',applicationId)));if(missionId)await clean('mission',()=>ok(admin.from('missions').delete().eq('id',missionId)));if(merchantId)await clean('merchant',()=>ok(admin.from('merchant_profiles').delete().eq('id',merchantId)));if(opsId){await clean('ops audit',()=>ok(admin.from('ops_audit_log').delete().eq('actor_ops_member_id',opsId)));await clean('ops member',()=>ok(admin.from('kinnso_ops_members').delete().eq('id',opsId)));}for(const id of users)await clean('user',()=>ok(admin.auth.admin.deleteUser(id)));
  if(errors.length){testInfo.annotations.push({type:'cleanup failures',description:errors.join(', ')});if(!failed)throw Error('Synthetic collaboration cleanup failed: '+errors.join(', '));}
 }
});
