import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {loadEnvFile} from 'node:process';
import {createClient} from '@supabase/supabase-js';
import {execFileSync} from 'node:child_process';
import {verifyTestTarget} from '../../scripts/verify-test-target.mjs';
loadEnvFile('.env.test');verifyTestTarget();
const boundedFetch:typeof fetch=(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(10000)});
const admin=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false},global:{fetch:boundedFetch}});
const ok=async(promise:PromiseLike<any>)=>{const r=await promise;expect(r.error).toBeNull();return r.data;};
async function signIn(page:Page,user:{email:string;password:string;id:string}){
 page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(15000);
 await page.goto('/en/sign-in?next=/en/merchant');await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill(user.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/en/merchant');
 await expect.poll(async()=>{const r=await page.request.get('/api/session'),body=await r.json();return r.ok()&&body.data?.id===user.id;}).toBe(true);
}
test('U04 invitation is persisted once, privately reviewed/cancelled, accepted once and revoked membership loses same-session access',async({page,browser,baseURL},testInfo)=>{
 test.setTimeout(150000);expect(new URL(baseURL!).origin).toBe('http://127.0.0.1:3495');const users:string[]=[],contexts:Awaited<ReturnType<typeof browser.newContext>>[]=[];let company:string|null=null,failed=false;
 const responses:{endpoint:string;status:number;code?:string}[]=[];page.on('response',async response=>{const endpoint=new URL(response.url()).pathname;if(!endpoint.startsWith('/api/merchant'))return;const body=await response.json().catch(()=>({}));responses.push({endpoint,status:response.status(),code:body.code});});
 async function actor(){const email=`synthetic-n11-inv-${randomUUID()}@example.test`,password=`Synthetic!${randomUUID()}`,user=(await ok(admin.auth.admin.createUser({email,password,email_confirm:true}))).user;users.push(user.id);const client=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_ANON_KEY!,{auth:{persistSession:false},global:{fetch:boundedFetch}});await ok(client.auth.signInWithPassword({email,password}));return{id:user.id,email,password,client};}
 try{
  const owner=await actor(),recipient=await actor(),foreign=await actor();company=(await ok(admin.from('merchant_profiles').insert({user_id:owner.id,company_name:'Synthetic invitation company',contact_email:owner.email}).select('id').single())).id;
  const branch=randomUUID(),command=(input:object)=>ok(owner.client.rpc('apply_kinnso_merchant_command',{p_merchant_id:company,p_request_id:randomUUID(),p_command:input}));await command({type:'createBranch',id:branch,name:'Synthetic invitation branch'});
  await signIn(page,owner);await expect(page.getByLabel('Company',{exact:true})).toHaveValue(company!);await expect(page.getByRole('heading',{name:'Invite a company colleague',exact:true})).toBeVisible();
  await page.getByLabel('Recipient email',{exact:true}).fill(recipient.email);await page.getByLabel('Private invitation label',{exact:true}).fill('Synthetic invited colleague');await page.getByLabel('Invitation role',{exact:true}).selectOption('clerk');await page.getByRole('group',{name:'Invitation branches',exact:true}).getByLabel('Synthetic invitation branch',{exact:true}).check();await page.getByLabel('Invitation reason',{exact:true}).fill('Synthetic explicit invitation review');
  const commands:unknown[]=[];let attempts=0;await page.route('**/api/merchant/invitations',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}commands.push(route.request().postDataJSON());const response=await route.fetch();if(++attempts===1)await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,code:'UNAVAILABLE'})});else await route.fulfill({response});});
  await page.getByRole('button',{name:'Create private invitation',exact:true}).click();await expect(page.getByRole('button',{name:'Retry invitation request',exact:true})).toBeVisible();await expect(page.getByLabel('Private invitation link',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Recipient email',{exact:true})).toBeDisabled();await expect(page.getByLabel('Company',{exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Retry invitation request',exact:true}).click();const linkInput=page.getByLabel('Private invitation link',{exact:true});await expect(linkInput).toBeVisible();const link=await linkInput.inputValue(),token=new URL(link).hash.slice(8);expect(token).toMatch(/^[0-9a-f]{64}$/);expect(commands).toHaveLength(2);expect(commands[1]).toEqual(commands[0]);
  const listing=await page.request.get('/api/merchant/invitations?id='+company),directory=await listing.json();expect(listing.headers()['cache-control']).toContain('private');expect(listing.headers()['cache-control']).toContain('no-store');expect(directory.data.invitations).toHaveLength(1);expect(JSON.stringify(directory)).not.toContain(token);expect(JSON.stringify(directory)).not.toContain(recipient.email);expect(await page.evaluate(()=>JSON.stringify([Object.keys(localStorage).map(key=>localStorage.getItem(key)),Object.keys(sessionStorage).map(key=>sessionStorage.getItem(key))]))).not.toContain(token);
  const foreignContext=await browser.newContext({baseURL});contexts.push(foreignContext);const foreignPage=await foreignContext.newPage();await signIn(foreignPage,foreign);await foreignPage.goto(link);await foreignPage.getByRole('button',{name:'Review invitation',exact:true}).click();await expect(foreignPage.getByRole('heading',{name:'Synthetic invitation company',exact:true})).toHaveCount(0);await expect(foreignPage.getByRole('button',{name:'Accept invitation',exact:true})).toHaveCount(0);
  const context=await browser.newContext({baseURL});contexts.push(context);const receiving=await context.newPage();await signIn(receiving,recipient);let accepts=0;receiving.on('request',request=>{if(request.url().endsWith('/api/merchant/invitations/recipient')&&request.method()==='POST'&&request.postDataJSON().action==='accept')accepts++;});
  await receiving.goto(link);await receiving.getByRole('button',{name:'Review invitation',exact:true}).click();await expect(receiving.getByRole('heading',{name:'Synthetic invitation company',exact:true})).toBeVisible();await expect(receiving.getByText('Branch clerk · Synthetic invitation branch',{exact:true})).toBeVisible();expect((await recipient.client.rpc('get_kinnso_merchant_workspace',{p_merchant_id:company})).error?.message).toBe('forbidden');
  await receiving.getByRole('button',{name:'Cancel invitation',exact:true}).click();expect(accepts).toBe(0);await expect(receiving.getByRole('button',{name:'Accept invitation',exact:true})).toHaveCount(0);
  await receiving.goto(link);await receiving.getByRole('button',{name:'Review invitation',exact:true}).click();
  const acceptanceBodies:unknown[]=[];let acceptAttempts=0;await receiving.route('**/api/merchant/invitations/recipient',async route=>{const body=route.request().postDataJSON();if(body.action!=='accept'){await route.continue();return;}acceptanceBodies.push(body);const response=await route.fetch();if(++acceptAttempts===1)await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,code:'UNAVAILABLE'})});else await route.fulfill({response});});
  await receiving.getByRole('button',{name:'Accept invitation',exact:true}).click();await expect(receiving.getByRole('button',{name:'Retry invitation acceptance',exact:true})).toBeVisible();await expect(receiving.getByRole('button',{name:'Cancel invitation',exact:true})).toBeDisabled();await receiving.getByRole('button',{name:'Retry invitation acceptance',exact:true}).click();await expect(receiving.getByRole('status').filter({hasText:'Invitation accepted and current company access confirmed.'})).toBeVisible();expect(acceptanceBodies).toHaveLength(2);expect(acceptanceBodies[1]).toEqual(acceptanceBodies[0]);
  const current=await ok(recipient.client.rpc('get_kinnso_merchant_workspace',{p_merchant_id:company}));expect(current.role).toBe('clerk');expect(current.branches.map((b:any)=>b.id)).toEqual([branch]);
  const audit=execFileSync('docker',['exec','supabase_db_kinnsoos-b1-20261002','psql','-U','postgres','-d','postgres','-X','-Atq','-c',`select action,count(*) from kinnso_internal.merchant_audit where merchant_id='${company}' and action in ('createInvitation','acceptInvitation') group by action order by action;`],{encoding:'utf8'});expect(audit.trim()).toBe('acceptInvitation|1\ncreateInvitation|1');
  await receiving.getByRole('link',{name:'Open merchant workspace',exact:true}).click();await expect(receiving.getByRole('heading',{name:'Redeem at this branch',exact:true})).toBeVisible();await command({type:'setMember',userId:recipient.id,role:'clerk',branchIds:[branch],active:false,reason:'Synthetic offboarding'});await receiving.getByRole('button',{name:'Refresh workspace',exact:true}).click();await expect(receiving.getByRole('heading',{name:'Redeem at this branch',exact:true})).toHaveCount(0);
  const replay=await receiving.evaluate(async body=>{const r=await fetch('/api/merchant/invitations/recipient',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return r.status;},acceptanceBodies[0]);expect(replay).toBe(403);
  await page.getByRole('button',{name:'Clear private link',exact:true}).click();await page.goto('/zh-HK/merchant');await expect(page.getByRole('heading',{name:'邀請公司同事',exact:true})).toBeVisible();await expect(page.getByLabel('收件人電郵',{exact:true})).toBeVisible();await page.setViewportSize({width:320,height:800});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.screenshot({path:'evidence/merchant-invitation-320.png',fullPage:true});
 }catch(error){failed=true;console.info('Bounded API statuses',JSON.stringify(responses));await testInfo.attach('bounded-api-statuses',{body:JSON.stringify(responses),contentType:'application/json'});throw error;}finally{const errors:string[]=[];for(const context of contexts){try{await context.close();}catch{errors.push('browser context');}}if(company){try{await ok(admin.from('merchant_profiles').delete().eq('id',company));}catch{errors.push('merchant');}}for(const id of users){try{await ok(admin.auth.admin.deleteUser(id));}catch{errors.push('auth');}}if(errors.length){testInfo.annotations.push({type:'cleanup failures',description:errors.join(',')});if(!failed)throw Error('Synthetic invitation cleanup failed: '+errors.join(','));}}
});
test('signed-out invitation never puts fragment token into server requests or login next',async({page})=>{
 const token='12'.repeat(32),requests:string[]=[];page.on('request',request=>requests.push(request.url()));const response=await page.goto('/en/merchant/invitation#invite='+token);expect(response?.headers()['cache-control']).toContain('private');expect(response?.headers()['cache-control']).toContain('no-store');await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content',/noindex/);await expect(page.getByRole('heading',{name:'Company invitation',exact:true})).toBeVisible();const login=page.getByRole('main').getByRole('link',{name:'Sign in to continue',exact:true});await expect(login).toHaveAttribute('href','/en/sign-in?next=/en/merchant/invitation');await expect.poll(()=>page.evaluate(()=>location.hash)).toBe('');expect(requests.some(url=>url.includes(token))).toBe(false);await expect(page.getByRole('button',{name:'Review invitation',exact:true})).toHaveCount(0);
});
